import React, { createContext, useContext, useState, useEffect } from 'react';

// Traductions
const translations = {
  fr: {
    // Common
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    generate: 'Générer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',

    // Login page
    loginSignin: 'Connexion',
    loginSignup: 'Inscription',
    loginConnectToContinue: 'Connecte-toi pour continuer',
    loginCreateAccount: 'Crée ton compte gratuit',
    loginEmail: 'Adresse email (Gmail de préférence)',
    loginPassword: 'Mot de passe',
    loginName: 'Nom (optionnel)',
    loginSubmitSignin: 'Se connecter',
    loginSubmitSignup: 'Créer mon compte',
    loginMagicLink: 'Connexion par lien magique (sans mot de passe)',
    loginForgot: 'Mot de passe oublié ?',
    loginSmsDemo: 'Connexion SMS (démo)',
    loginOrOffline: 'ou mode hors-ligne',
    loginBackHome: "← Retour à l'accueil",
    loginHowItWorks: 'Comment ça marche',
    loginLegal: 'CGU & Confidentialité',
    loginWaitingForConfirm: 'En attente de la confirmation…',
    loginEmailMinChars: '6 caractères minimum',
    loginExpiresIn: 'Expire dans',
    loginResendBtn: 'Renvoyer le lien',
    loginResendSent: 'Envoi…',
    loginResendCooldown: 'Patiente 10 min',
    loginIdleNotice: "Vous avez été déconnecté après 1h ou plus d'inactivité. Vous pouvez fermer ce message et vous reconnecter.",

    // Auth (legacy)
    login: 'Connexion',
    logout: 'Déconnexion',
    loginWithGoogle: 'Continuer avec Google',
    loginWithSMS: 'Connexion SMS (Hors Ligne)',
    phoneNumber: 'Numéro de téléphone',
    sendCode: 'Envoyer le code',
    verifyCode: 'Vérifier le code',
    invalidCode: 'Code invalide',
    codeSent: 'Code envoyé !',
    
    // Dashboard
    dashboard: 'Tableau de bord',
    projects: 'Projets',
    newProject: 'Nouveau Projet',
    whatToDo: 'Que souhaitez-vous faire ?',
    chooseWorkMode: 'Choisissez votre mode de travail',
    
    // Modes
    online: 'En ligne',
    offline: 'Hors ligne',
    onlineChat: 'Interaction IA en ligne',
    offlineChat: 'Interaction IA hors ligne',
    onlineCreate: 'Création en ligne',
    offlineCreate: 'Création hors ligne',
    
    // Create
    createTitle: 'Création IA Sans Limites',
    describeApp: 'Décrivez votre application',
    aiGeneratesAll: "L'IA génère tout automatiquement",
    unlimitedCreation: 'Création Illimitée',
    describeWhatYouWant: 'Décrivez ce que vous voulez créer',
    generationInProgress: 'Génération en cours...',
    appGenerated: 'Application générée !',
    codeReadyExport: 'Code généré et prêt à exporter',
    
    // Preview
    preview: 'Prévisualisation',
    previewWeb: 'Prévisualiser Web',
    previewApp: 'Prévisualiser App',
    previewPDF: 'Prévisualiser PDF',
    previewDOCX: 'Prévisualiser DOCX',
    
    // Export
    export: 'Export',
    exportAPK: 'Export Mobile (APK)',
    exportEXE: 'Export Desktop (EXE)',
    exportWeb: 'Déploiement Web',
    downloadSource: 'Télécharger le code source',
    installOnAndroid: 'Installez sur Android directement',
    downloadInstaller: "Téléchargez l'installateur Windows",
    deployVercel: 'Déployez sur Vercel, Netlify ou votre hébergeur',
    
    // Wizard
    wizardTitle: 'Assistant de Création',
    step: 'Étape',
    whatTypeApp: "Quel type d'application ?",
    chooseTemplate: 'Choisissez le modèle qui correspond le mieux',
    giveName: 'Donnez un nom',
    whatWillBeCalled: "Comment s'appellera votre application ?",
    chooseColors: 'Choisissez vos couleurs',
    selectPalette: 'Sélectionnez une palette de couleurs',
    targetPlatform: 'Plateforme cible',
    whereUsed: 'Où sera utilisée votre application ?',
    advancedOptions: 'Options avancées',
    customizeFeatures: 'Personnalisez les fonctionnalités',
    authentication: 'Authentification',
    loginSignupSystem: 'Système de login/signup',
    database: 'Base de données',
    persistentStorage: 'Stockage de données persistant',
    interfaceLanguage: "Langue de l'interface",
    summary: 'Résumé de votre application',
    generateApp: "Générer l'Application",
    appReady: 'Application prête à être exportée',
    
    // App Types
    ecommerce: 'E-Commerce',
    blog: 'Blog/CMS',
    social: 'Réseau Social',
    chat: 'Messagerie',
    portfolio: 'Portfolio',
    dashboardType: 'Dashboard',
    booking: 'Réservation',
    media: 'Média/Streaming',
    maps: 'Géolocalisation',
    utility: 'Utilitaire',
    music: 'Audio/Musique',
    custom: 'Personnalisé',
    
    // Platforms
    web: 'Web',
    mobile: 'Mobile',
    desktop: 'Desktop',
    allPlatforms: 'Toutes',

    // Dashboard
    dashProjects: 'Projets',
    dashNewProject: 'Nouveau Projet',
    dashSwitchAccount: 'Changer de compte',
    dashLogout: 'Déconnexion',
    dashOnline: 'En ligne',
    dashOffline: 'Hors ligne',
    dashAiAvailable: 'IA Disponible',
    dashTitle: 'CodeForge AI',
    dashSubtitle: 'Création Sans Limites',
    dashWhatToDo: 'Que souhaitez-vous faire ?',
    dashChooseMode: 'Choisissez votre mode de travail',
    dashEmptyHint: "✨ Aucun projet pour l'instant — choisis un mode ci-dessous pour commencer (tout est gratuit et sans limites).",
    dashWizard: 'Assistant Guidé',
    dashWizardDesc: 'Créez votre app étape par étape avec des questions simples',
    dashChat: 'Interaction',
    dashChatBadgeOn: 'IA EN LIGNE',
    dashChatDescOn: 'Discutez avec une IA puissante',
    dashChatBadgeOff: 'IA HORS LIGNE',
    dashChatDescOff: 'IA locale (Ollama) sans connexion',
    dashCreate: 'Création',
    dashCreateBadgeOn: 'EN LIGNE',
    dashCreateDescOn: 'Générez apps mobile, web, desktop',
    dashCreateBadgeOff: 'HORS LIGNE',
    dashCreateDescOff: 'Générez apps avec IA locale (Ollama)',
    dashInfoOnline: '💡 Mode en ligne : IA puissante avec Ollama distant',
    dashInfoOffline: '🔌 Mode hors ligne : Nécessite Ollama installé localement',
    dashCollapseSidebar: 'Réduire la barre',
    dashExpandSidebar: 'Afficher les projets'
  },
  
  en: {
    // Common
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    generate: 'Generate',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    yes: 'Yes',
    no: 'No',

    // Login page
    loginSignin: 'Sign in',
    loginSignup: 'Sign up',
    loginConnectToContinue: 'Sign in to continue',
    loginCreateAccount: 'Create your free account',
    loginEmail: 'Email address (Gmail preferred)',
    loginPassword: 'Password',
    loginName: 'Name (optional)',
    loginSubmitSignin: 'Sign in',
    loginSubmitSignup: 'Create my account',
    loginMagicLink: 'Magic link sign-in (no password)',
    loginForgot: 'Forgot your password?',
    loginSmsDemo: 'SMS sign-in (demo)',
    loginOrOffline: 'or offline mode',
    loginBackHome: '← Back to home',
    loginHowItWorks: 'How it works',
    loginLegal: 'Terms & Privacy',
    loginWaitingForConfirm: 'Waiting for confirmation…',
    loginEmailMinChars: '6 characters minimum',
    loginExpiresIn: 'Expires in',
    loginResendBtn: 'Resend link',
    loginResendSent: 'Sending…',
    loginResendCooldown: 'Wait 10 min',
    loginIdleNotice: "You were logged out after 1h+ of inactivity. Close this message and sign in again.",
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    
    // Auth
    login: 'Login',
    logout: 'Logout',
    loginWithGoogle: 'Continue with Google',
    loginWithSMS: 'SMS Login (Offline)',
    phoneNumber: 'Phone number',
    sendCode: 'Send code',
    verifyCode: 'Verify code',
    invalidCode: 'Invalid code',
    codeSent: 'Code sent!',
    
    // Dashboard
    dashboard: 'Dashboard',
    projects: 'Projects',
    newProject: 'New Project',
    whatToDo: 'What would you like to do?',
    chooseWorkMode: 'Choose your work mode',
    
    // Modes
    online: 'Online',
    offline: 'Offline',
    onlineChat: 'Online AI Chat',
    offlineChat: 'Offline AI Chat',
    onlineCreate: 'Online Creation',
    offlineCreate: 'Offline Creation',
    
    // Create
    createTitle: 'Unlimited AI Creation',
    describeApp: 'Describe your application',
    aiGeneratesAll: 'AI generates everything automatically',
    unlimitedCreation: 'Unlimited Creation',
    describeWhatYouWant: 'Describe what you want to create',
    generationInProgress: 'Generation in progress...',
    appGenerated: 'Application generated!',
    codeReadyExport: 'Code generated and ready to export',
    
    // Preview
    preview: 'Preview',
    previewWeb: 'Preview Web',
    previewApp: 'Preview App',
    previewPDF: 'Preview PDF',
    previewDOCX: 'Preview DOCX',
    
    // Export
    export: 'Export',
    exportAPK: 'Mobile Export (APK)',
    exportEXE: 'Desktop Export (EXE)',
    exportWeb: 'Web Deployment',
    downloadSource: 'Download source code',
    installOnAndroid: 'Install on Android directly',
    downloadInstaller: 'Download Windows installer',
    deployVercel: 'Deploy on Vercel, Netlify or your host',
    
    // Wizard
    wizardTitle: 'Creation Wizard',
    step: 'Step',
    whatTypeApp: 'What type of application?',
    chooseTemplate: 'Choose the template that fits best',
    giveName: 'Give it a name',
    whatWillBeCalled: 'What will your application be called?',
    chooseColors: 'Choose your colors',
    selectPalette: 'Select a color palette',
    targetPlatform: 'Target platform',
    whereUsed: 'Where will your application be used?',
    advancedOptions: 'Advanced options',
    customizeFeatures: 'Customize features',
    authentication: 'Authentication',
    loginSignupSystem: 'Login/signup system',
    database: 'Database',
    persistentStorage: 'Persistent data storage',
    interfaceLanguage: 'Interface language',
    summary: 'Your application summary',
    generateApp: 'Generate Application',
    appReady: 'Application ready to export',
    
    // App Types
    ecommerce: 'E-Commerce',
    blog: 'Blog/CMS',
    social: 'Social Network',
    chat: 'Messaging',
    portfolio: 'Portfolio',
    dashboardType: 'Dashboard',
    booking: 'Booking',
    media: 'Media/Streaming',
    maps: 'Geolocation',
    utility: 'Utility',
    music: 'Audio/Music',
    custom: 'Custom',
    
    // Platforms
    web: 'Web',
    mobile: 'Mobile',
    desktop: 'Desktop',
    allPlatforms: 'All',

    // Dashboard
    dashProjects: 'Projects',
    dashNewProject: 'New Project',
    dashSwitchAccount: 'Switch account',
    dashLogout: 'Sign out',
    dashOnline: 'Online',
    dashOffline: 'Offline',
    dashAiAvailable: 'AI available',
    dashTitle: 'CodeForge AI',
    dashSubtitle: 'Unlimited Creation',
    dashWhatToDo: 'What would you like to do?',
    dashChooseMode: 'Choose your work mode',
    dashEmptyHint: '✨ No projects yet — pick a mode below to get started (free and unlimited).',
    dashWizard: 'Guided Wizard',
    dashWizardDesc: 'Create your app step by step with simple questions',
    dashChat: 'Chat',
    dashChatBadgeOn: 'ONLINE AI',
    dashChatDescOn: 'Chat with a powerful AI',
    dashChatBadgeOff: 'OFFLINE AI',
    dashChatDescOff: 'Local AI (Ollama) without internet',
    dashCreate: 'Create',
    dashCreateBadgeOn: 'ONLINE',
    dashCreateDescOn: 'Generate mobile, web, desktop apps',
    dashCreateBadgeOff: 'OFFLINE',
    dashCreateDescOff: 'Generate apps with local AI (Ollama)',
    dashInfoOnline: '💡 Online mode: Powerful AI with remote Ollama',
    dashInfoOffline: '🔌 Offline mode: Requires Ollama installed locally',
    dashCollapseSidebar: 'Collapse sidebar',
    dashExpandSidebar: 'Show projects'
  },

  // ========== ESPAÑOL ==========
  es: {
    back: 'Volver', next: 'Siguiente', previous: 'Anterior', generate: 'Generar',
    loading: 'Cargando…', error: 'Error', success: 'Éxito', cancel: 'Cancelar',
    save: 'Guardar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', yes: 'Sí', no: 'No',
    loginSignin: 'Iniciar sesión', loginSignup: 'Registrarse',
    loginConnectToContinue: 'Inicia sesión para continuar',
    loginCreateAccount: 'Crea tu cuenta gratuita',
    loginEmail: 'Correo electrónico (Gmail preferido)',
    loginPassword: 'Contraseña', loginName: 'Nombre (opcional)',
    loginSubmitSignin: 'Iniciar sesión', loginSubmitSignup: 'Crear mi cuenta',
    loginMagicLink: 'Acceso por enlace mágico (sin contraseña)',
    loginForgot: '¿Olvidaste tu contraseña?',
    loginSmsDemo: 'Acceso por SMS (demo)',
    loginOrOffline: 'o modo sin conexión',
    loginBackHome: '← Volver al inicio',
    loginHowItWorks: 'Cómo funciona', loginLegal: 'Términos y Privacidad',
    loginWaitingForConfirm: 'Esperando confirmación…',
    loginEmailMinChars: '6 caracteres mínimo', loginExpiresIn: 'Expira en',
    loginResendBtn: 'Reenviar enlace', loginResendSent: 'Enviando…',
    loginResendCooldown: 'Espera 10 min',
    loginIdleNotice: 'Has sido desconectado tras 1 h o más de inactividad. Cierra este mensaje y vuelve a iniciar sesión.',
    dashProjects: 'Proyectos', dashNewProject: 'Nuevo proyecto', dashSwitchAccount: 'Cambiar de cuenta', dashLogout: 'Cerrar sesión',
    dashOnline: 'En línea', dashOffline: 'Sin conexión', dashAiAvailable: 'IA disponible',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Creación sin límites',
    dashWhatToDo: '¿Qué quieres hacer?', dashChooseMode: 'Elige tu modo de trabajo',
    dashEmptyHint: '✨ Aún no hay proyectos — elige un modo para empezar (gratis e ilimitado).',
    dashWizard: 'Asistente guiado', dashWizardDesc: 'Crea tu app paso a paso con preguntas sencillas',
    dashChat: 'Interacción', dashChatBadgeOn: 'IA EN LÍNEA', dashChatDescOn: 'Chatea con una IA potente',
    dashChatBadgeOff: 'IA SIN CONEXIÓN', dashChatDescOff: 'IA local (Ollama) sin internet',
    dashCreate: 'Crear', dashCreateBadgeOn: 'EN LÍNEA', dashCreateDescOn: 'Genera apps móvil, web, desktop',
    dashCreateBadgeOff: 'SIN CONEXIÓN', dashCreateDescOff: 'Genera apps con IA local (Ollama)',
    dashInfoOnline: '💡 Modo en línea: IA potente con Ollama remoto',
    dashInfoOffline: '🔌 Modo sin conexión: requiere Ollama instalado localmente',
    dashCollapseSidebar: 'Ocultar barra', dashExpandSidebar: 'Mostrar proyectos',
  },

  // ========== DEUTSCH ==========
  de: {
    back: 'Zurück', next: 'Weiter', previous: 'Vorherige', generate: 'Generieren',
    loading: 'Lädt…', error: 'Fehler', success: 'Erfolg', cancel: 'Abbrechen',
    save: 'Speichern', delete: 'Löschen', edit: 'Bearbeiten', close: 'Schließen', yes: 'Ja', no: 'Nein',
    loginSignin: 'Anmelden', loginSignup: 'Registrieren',
    loginConnectToContinue: 'Melde dich an, um fortzufahren',
    loginCreateAccount: 'Erstelle dein kostenloses Konto',
    loginEmail: 'E-Mail-Adresse (Gmail bevorzugt)',
    loginPassword: 'Passwort', loginName: 'Name (optional)',
    loginSubmitSignin: 'Anmelden', loginSubmitSignup: 'Konto erstellen',
    loginMagicLink: 'Magic-Link-Anmeldung (ohne Passwort)',
    loginForgot: 'Passwort vergessen?',
    loginSmsDemo: 'SMS-Anmeldung (Demo)',
    loginOrOffline: 'oder Offline-Modus',
    loginBackHome: '← Zurück zur Startseite',
    loginHowItWorks: 'Wie es funktioniert', loginLegal: 'AGB & Datenschutz',
    loginWaitingForConfirm: 'Warte auf Bestätigung…',
    loginEmailMinChars: 'Mindestens 6 Zeichen', loginExpiresIn: 'Läuft ab in',
    loginResendBtn: 'Link erneut senden', loginResendSent: 'Senden…',
    loginResendCooldown: '10 Min warten',
    loginIdleNotice: 'Du wurdest nach 1+ Stunde Inaktivität abgemeldet. Schließe diese Nachricht und melde dich erneut an.',
    dashProjects: 'Projekte', dashNewProject: 'Neues Projekt', dashSwitchAccount: 'Konto wechseln', dashLogout: 'Abmelden',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'KI verfügbar',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Grenzenlose Kreation',
    dashWhatToDo: 'Was möchtest du tun?', dashChooseMode: 'Wähle deinen Arbeitsmodus',
    dashEmptyHint: '✨ Noch keine Projekte — wähle unten einen Modus, um loszulegen (kostenlos & unbegrenzt).',
    dashWizard: 'Geführter Assistent', dashWizardDesc: 'Erstelle deine App Schritt für Schritt mit einfachen Fragen',
    dashChat: 'Chat', dashChatBadgeOn: 'ONLINE-KI', dashChatDescOn: 'Chatte mit einer leistungsstarken KI',
    dashChatBadgeOff: 'OFFLINE-KI', dashChatDescOff: 'Lokale KI (Ollama) ohne Internet',
    dashCreate: 'Erstellen', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Mobile-, Web- und Desktop-Apps erzeugen',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Apps mit lokaler KI (Ollama) erzeugen',
    dashInfoOnline: '💡 Online-Modus: leistungsstarke KI mit Remote-Ollama',
    dashInfoOffline: '🔌 Offline-Modus: erfordert lokal installiertes Ollama',
    dashCollapseSidebar: 'Leiste einklappen', dashExpandSidebar: 'Projekte anzeigen',
  },

  // ========== NEDERLANDS ==========
  nl: {
    back: 'Terug', next: 'Volgende', previous: 'Vorige', generate: 'Genereren',
    loading: 'Laden…', error: 'Fout', success: 'Gelukt', cancel: 'Annuleren',
    save: 'Opslaan', delete: 'Verwijderen', edit: 'Bewerken', close: 'Sluiten', yes: 'Ja', no: 'Nee',
    loginSignin: 'Inloggen', loginSignup: 'Aanmelden',
    loginConnectToContinue: 'Log in om door te gaan',
    loginCreateAccount: 'Maak je gratis account aan',
    loginEmail: 'E-mailadres (Gmail aanbevolen)',
    loginPassword: 'Wachtwoord', loginName: 'Naam (optioneel)',
    loginSubmitSignin: 'Inloggen', loginSubmitSignup: 'Account aanmaken',
    loginMagicLink: 'Inloggen via magic link (zonder wachtwoord)',
    loginForgot: 'Wachtwoord vergeten?',
    loginSmsDemo: 'SMS-login (demo)',
    loginOrOffline: 'of offline modus',
    loginBackHome: '← Terug naar home',
    loginHowItWorks: 'Hoe het werkt', loginLegal: 'Voorwaarden & Privacy',
    loginWaitingForConfirm: 'Wachten op bevestiging…',
    loginEmailMinChars: 'Minimaal 6 tekens', loginExpiresIn: 'Verloopt over',
    loginResendBtn: 'Link opnieuw versturen', loginResendSent: 'Bezig…',
    loginResendCooldown: 'Wacht 10 min',
    loginIdleNotice: 'Je bent uitgelogd na 1 uur of meer inactiviteit. Sluit dit bericht en log opnieuw in.',
    dashProjects: 'Projecten', dashNewProject: 'Nieuw project', dashSwitchAccount: 'Account wisselen', dashLogout: 'Uitloggen',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'AI beschikbaar',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Onbeperkt creëren',
    dashWhatToDo: 'Wat wil je doen?', dashChooseMode: 'Kies je werkmodus',
    dashEmptyHint: '✨ Nog geen projecten — kies hieronder een modus om te beginnen (gratis & onbeperkt).',
    dashWizard: 'Begeleide wizard', dashWizardDesc: 'Maak je app stap voor stap met simpele vragen',
    dashChat: 'Chat', dashChatBadgeOn: 'ONLINE AI', dashChatDescOn: 'Chat met een krachtige AI',
    dashChatBadgeOff: 'OFFLINE AI', dashChatDescOff: 'Lokale AI (Ollama) zonder internet',
    dashCreate: 'Maken', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Genereer mobiele, web- en desktop-apps',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Genereer apps met lokale AI (Ollama)',
    dashInfoOnline: '💡 Online modus: krachtige AI met externe Ollama',
    dashInfoOffline: '🔌 Offline modus: vereist Ollama lokaal geïnstalleerd',
    dashCollapseSidebar: 'Balk inklappen', dashExpandSidebar: 'Projecten tonen',
  },

  // ========== РУССКИЙ ==========
  ru: {
    back: 'Назад', next: 'Далее', previous: 'Предыдущее', generate: 'Создать',
    loading: 'Загрузка…', error: 'Ошибка', success: 'Успех', cancel: 'Отмена',
    save: 'Сохранить', delete: 'Удалить', edit: 'Изменить', close: 'Закрыть', yes: 'Да', no: 'Нет',
    loginSignin: 'Войти', loginSignup: 'Регистрация',
    loginConnectToContinue: 'Войдите, чтобы продолжить',
    loginCreateAccount: 'Создайте бесплатный аккаунт',
    loginEmail: 'Адрес эл. почты (предпочтительно Gmail)',
    loginPassword: 'Пароль', loginName: 'Имя (необязательно)',
    loginSubmitSignin: 'Войти', loginSubmitSignup: 'Создать аккаунт',
    loginMagicLink: 'Вход по волшебной ссылке (без пароля)',
    loginForgot: 'Забыли пароль?',
    loginSmsDemo: 'Вход по SMS (демо)',
    loginOrOffline: 'или офлайн-режим',
    loginBackHome: '← На главную',
    loginHowItWorks: 'Как это работает', loginLegal: 'Условия и Конфиденциальность',
    loginWaitingForConfirm: 'Ожидание подтверждения…',
    loginEmailMinChars: 'Минимум 6 символов', loginExpiresIn: 'Истекает через',
    loginResendBtn: 'Отправить ссылку снова', loginResendSent: 'Отправка…',
    loginResendCooldown: 'Подождите 10 мин',
    loginIdleNotice: 'Вы вышли после 1+ часа бездействия. Закройте это сообщение и войдите снова.',
    dashProjects: 'Проекты', dashNewProject: 'Новый проект', dashSwitchAccount: 'Сменить аккаунт', dashLogout: 'Выйти',
    dashOnline: 'Онлайн', dashOffline: 'Офлайн', dashAiAvailable: 'ИИ доступен',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Создание без ограничений',
    dashWhatToDo: 'Что вы хотите сделать?', dashChooseMode: 'Выберите режим работы',
    dashEmptyHint: '✨ Пока нет проектов — выберите режим ниже, чтобы начать (бесплатно и без ограничений).',
    dashWizard: 'Помощник', dashWizardDesc: 'Создайте приложение шаг за шагом с простыми вопросами',
    dashChat: 'Чат', dashChatBadgeOn: 'ОНЛАЙН-ИИ', dashChatDescOn: 'Общайтесь с мощным ИИ',
    dashChatBadgeOff: 'ОФЛАЙН-ИИ', dashChatDescOff: 'Локальный ИИ (Ollama) без интернета',
    dashCreate: 'Создать', dashCreateBadgeOn: 'ОНЛАЙН', dashCreateDescOn: 'Создавайте мобильные, веб- и десктоп-приложения',
    dashCreateBadgeOff: 'ОФЛАЙН', dashCreateDescOff: 'Создавайте приложения с локальным ИИ (Ollama)',
    dashInfoOnline: '💡 Онлайн-режим: мощный ИИ с удалённым Ollama',
    dashInfoOffline: '🔌 Офлайн-режим: требуется установленный локально Ollama',
    dashCollapseSidebar: 'Свернуть панель', dashExpandSidebar: 'Показать проекты',
  },

  // ========== 中文 简体 (Chinese Simplified) ==========
  zh: {
    back: '返回', next: '下一步', previous: '上一步', generate: '生成',
    loading: '加载中…', error: '错误', success: '成功', cancel: '取消',
    save: '保存', delete: '删除', edit: '编辑', close: '关闭', yes: '是', no: '否',
    loginSignin: '登录', loginSignup: '注册',
    loginConnectToContinue: '登录以继续',
    loginCreateAccount: '免费创建账户',
    loginEmail: '电子邮件 (推荐使用 Gmail)',
    loginPassword: '密码', loginName: '姓名 (可选)',
    loginSubmitSignin: '登录', loginSubmitSignup: '创建账户',
    loginMagicLink: '魔法链接登录 (无需密码)',
    loginForgot: '忘记密码？',
    loginSmsDemo: '短信登录 (演示)',
    loginOrOffline: '或离线模式',
    loginBackHome: '← 返回首页',
    loginHowItWorks: '使用说明', loginLegal: '服务条款与隐私',
    loginWaitingForConfirm: '等待确认…',
    loginEmailMinChars: '至少 6 个字符', loginExpiresIn: '到期时间',
    loginResendBtn: '重新发送链接', loginResendSent: '发送中…',
    loginResendCooldown: '请等待 10 分钟',
    loginIdleNotice: '由于超过 1 小时未活动，您已被自动注销。请关闭此消息后重新登录。',
    dashProjects: '项目', dashNewProject: '新建项目', dashSwitchAccount: '切换账户', dashLogout: '退出登录',
    dashOnline: '在线', dashOffline: '离线', dashAiAvailable: 'AI 可用',
    dashTitle: 'CodeForge AI', dashSubtitle: '无限创作',
    dashWhatToDo: '你想做什么？', dashChooseMode: '选择你的工作模式',
    dashEmptyHint: '✨ 还没有项目 — 选择下方模式开始吧（免费、无限制）。',
    dashWizard: '引导式向导', dashWizardDesc: '通过简单的问题逐步创建你的应用',
    dashChat: '聊天', dashChatBadgeOn: '在线 AI', dashChatDescOn: '与强大的 AI 交流',
    dashChatBadgeOff: '离线 AI', dashChatDescOff: '本地 AI (Ollama)，无需联网',
    dashCreate: '创建', dashCreateBadgeOn: '在线', dashCreateDescOn: '生成移动端、网页、桌面应用',
    dashCreateBadgeOff: '离线', dashCreateDescOff: '使用本地 AI (Ollama) 生成应用',
    dashInfoOnline: '💡 在线模式：使用远程 Ollama 的强大 AI',
    dashInfoOffline: '🔌 离线模式：需要本地安装 Ollama',
    dashCollapseSidebar: '收起侧栏', dashExpandSidebar: '显示项目',
  },

  // ========== 中文 繁體 (Chinese Traditional) ==========
  'zh-TW': {
    back: '返回', next: '下一步', previous: '上一步', generate: '生成',
    loading: '載入中…', error: '錯誤', success: '成功', cancel: '取消',
    save: '儲存', delete: '刪除', edit: '編輯', close: '關閉', yes: '是', no: '否',
    loginSignin: '登入', loginSignup: '註冊',
    loginConnectToContinue: '登入以繼續',
    loginCreateAccount: '免費建立帳戶',
    loginEmail: '電子郵件 (建議使用 Gmail)',
    loginPassword: '密碼', loginName: '姓名 (可選)',
    loginSubmitSignin: '登入', loginSubmitSignup: '建立帳戶',
    loginMagicLink: '魔法連結登入 (免密碼)',
    loginForgot: '忘記密碼？',
    loginSmsDemo: '簡訊登入 (示範)',
    loginOrOffline: '或離線模式',
    loginBackHome: '← 返回首頁',
    loginHowItWorks: '使用說明', loginLegal: '服務條款與隱私',
    loginWaitingForConfirm: '等待確認…',
    loginEmailMinChars: '至少 6 個字元', loginExpiresIn: '到期時間',
    loginResendBtn: '重新傳送連結', loginResendSent: '傳送中…',
    loginResendCooldown: '請等待 10 分鐘',
    loginIdleNotice: '由於超過 1 小時未操作，您已被自動登出。請關閉此訊息後重新登入。',
    dashProjects: '專案', dashNewProject: '新增專案', dashSwitchAccount: '切換帳戶', dashLogout: '登出',
    dashOnline: '線上', dashOffline: '離線', dashAiAvailable: 'AI 可用',
    dashTitle: 'CodeForge AI', dashSubtitle: '無限創作',
    dashWhatToDo: '你想做什麼？', dashChooseMode: '選擇你的工作模式',
    dashEmptyHint: '✨ 還沒有專案 — 選擇下方模式開始吧（免費、無限制）。',
    dashWizard: '引導式精靈', dashWizardDesc: '透過簡單的問題逐步建立你的應用',
    dashChat: '聊天', dashChatBadgeOn: '線上 AI', dashChatDescOn: '與強大的 AI 對話',
    dashChatBadgeOff: '離線 AI', dashChatDescOff: '本機 AI (Ollama)，無須連網',
    dashCreate: '建立', dashCreateBadgeOn: '線上', dashCreateDescOn: '產生行動、網頁、桌面應用',
    dashCreateBadgeOff: '離線', dashCreateDescOff: '使用本機 AI (Ollama) 產生應用',
    dashInfoOnline: '💡 線上模式：使用遠端 Ollama 的強大 AI',
    dashInfoOffline: '🔌 離線模式：需要本機安裝 Ollama',
    dashCollapseSidebar: '收合側邊欄', dashExpandSidebar: '顯示專案',
  },

  // ========== हिन्दी (Hindi) ==========
  hi: {
    back: 'वापस', next: 'अगला', previous: 'पिछला', generate: 'बनाएँ',
    loading: 'लोड हो रहा है…', error: 'त्रुटि', success: 'सफलता', cancel: 'रद्द करें',
    save: 'सहेजें', delete: 'हटाएँ', edit: 'संपादित करें', close: 'बंद करें', yes: 'हाँ', no: 'नहीं',
    loginSignin: 'साइन इन', loginSignup: 'साइन अप',
    loginConnectToContinue: 'जारी रखने के लिए साइन इन करें',
    loginCreateAccount: 'अपना मुफ़्त खाता बनाएँ',
    loginEmail: 'ईमेल पता (Gmail अनुशंसित)',
    loginPassword: 'पासवर्ड', loginName: 'नाम (वैकल्पिक)',
    loginSubmitSignin: 'साइन इन', loginSubmitSignup: 'खाता बनाएँ',
    loginMagicLink: 'मैजिक लिंक साइन-इन (बिना पासवर्ड)',
    loginForgot: 'पासवर्ड भूल गए?',
    loginSmsDemo: 'SMS साइन-इन (डेमो)',
    loginOrOffline: 'या ऑफ़लाइन मोड',
    loginBackHome: '← होम पर वापस',
    loginHowItWorks: 'यह कैसे काम करता है', loginLegal: 'नियम और गोपनीयता',
    loginWaitingForConfirm: 'पुष्टि की प्रतीक्षा है…',
    loginEmailMinChars: 'न्यूनतम 6 अक्षर', loginExpiresIn: 'समाप्त होगा',
    loginResendBtn: 'लिंक फिर भेजें', loginResendSent: 'भेज रहे हैं…',
    loginResendCooldown: '10 मिनट प्रतीक्षा करें',
    loginIdleNotice: '1 घंटे या अधिक की निष्क्रियता के बाद आपको लॉग आउट कर दिया गया है। यह संदेश बंद करें और फिर से साइन इन करें।',
    dashProjects: 'प्रोजेक्ट', dashNewProject: 'नया प्रोजेक्ट', dashSwitchAccount: 'खाता बदलें', dashLogout: 'लॉग आउट',
    dashOnline: 'ऑनलाइन', dashOffline: 'ऑफ़लाइन', dashAiAvailable: 'AI उपलब्ध',
    dashTitle: 'CodeForge AI', dashSubtitle: 'असीमित निर्माण',
    dashWhatToDo: 'आप क्या करना चाहते हैं?', dashChooseMode: 'अपना कार्य मोड चुनें',
    dashEmptyHint: '✨ अभी कोई प्रोजेक्ट नहीं — शुरू करने के लिए नीचे एक मोड चुनें (मुफ़्त और असीमित)।',
    dashWizard: 'गाइडेड विज़ार्ड', dashWizardDesc: 'सरल प्रश्नों के साथ चरण-दर-चरण अपनी ऐप बनाएं',
    dashChat: 'चैट', dashChatBadgeOn: 'ऑनलाइन AI', dashChatDescOn: 'शक्तिशाली AI से बातचीत करें',
    dashChatBadgeOff: 'ऑफ़लाइन AI', dashChatDescOff: 'इंटरनेट के बिना स्थानीय AI (Ollama)',
    dashCreate: 'बनाएं', dashCreateBadgeOn: 'ऑनलाइन', dashCreateDescOn: 'मोबाइल, वेब, डेस्कटॉप ऐप्स बनाएं',
    dashCreateBadgeOff: 'ऑफ़लाइन', dashCreateDescOff: 'स्थानीय AI (Ollama) से ऐप्स बनाएं',
    dashInfoOnline: '💡 ऑनलाइन मोड: रिमोट Ollama के साथ शक्तिशाली AI',
    dashInfoOffline: '🔌 ऑफ़लाइन मोड: स्थानीय रूप से Ollama इंस्टॉल होना आवश्यक',
    dashCollapseSidebar: 'साइडबार छुपाएं', dashExpandSidebar: 'प्रोजेक्ट दिखाएं',
  },

  // ========== বাংলা (Bengali) ==========
  bn: {
    back: 'ফিরে যান', next: 'পরবর্তী', previous: 'পূর্ববর্তী', generate: 'তৈরি করুন',
    loading: 'লোড হচ্ছে…', error: 'ত্রুটি', success: 'সফল', cancel: 'বাতিল',
    save: 'সংরক্ষণ', delete: 'মুছুন', edit: 'সম্পাদনা', close: 'বন্ধ', yes: 'হ্যাঁ', no: 'না',
    loginSignin: 'সাইন ইন', loginSignup: 'সাইন আপ',
    loginConnectToContinue: 'চালিয়ে যেতে সাইন ইন করুন',
    loginCreateAccount: 'আপনার বিনামূল্যে অ্যাকাউন্ট তৈরি করুন',
    loginEmail: 'ইমেইল ঠিকানা (Gmail অনুমোদিত)',
    loginPassword: 'পাসওয়ার্ড', loginName: 'নাম (ঐচ্ছিক)',
    loginSubmitSignin: 'সাইন ইন', loginSubmitSignup: 'অ্যাকাউন্ট তৈরি করুন',
    loginMagicLink: 'ম্যাজিক লিঙ্ক সাইন-ইন (পাসওয়ার্ড ছাড়া)',
    loginForgot: 'পাসওয়ার্ড ভুলে গেছেন?',
    loginSmsDemo: 'SMS সাইন-ইন (ডেমো)',
    loginOrOffline: 'বা অফলাইন মোড',
    loginBackHome: '← হোমে ফিরুন',
    loginHowItWorks: 'এটি কীভাবে কাজ করে', loginLegal: 'শর্তাবলী ও গোপনীয়তা',
    loginWaitingForConfirm: 'নিশ্চিতকরণের অপেক্ষায়…',
    loginEmailMinChars: 'কমপক্ষে ৬ অক্ষর', loginExpiresIn: 'মেয়াদ শেষ হবে',
    loginResendBtn: 'লিঙ্ক পুনরায় পাঠান', loginResendSent: 'পাঠানো হচ্ছে…',
    loginResendCooldown: '১০ মিনিট অপেক্ষা করুন',
    loginIdleNotice: '১ ঘণ্টা বা তার বেশি নিষ্ক্রিয়তার পর আপনি লগ আউট হয়েছেন। এই বার্তা বন্ধ করে আবার সাইন ইন করুন।',
    dashProjects: 'প্রকল্প', dashNewProject: 'নতুন প্রকল্প', dashSwitchAccount: 'অ্যাকাউন্ট বদলান', dashLogout: 'লগ আউট',
    dashOnline: 'অনলাইন', dashOffline: 'অফলাইন', dashAiAvailable: 'AI উপলব্ধ',
    dashTitle: 'CodeForge AI', dashSubtitle: 'সীমাহীন তৈরি',
    dashWhatToDo: 'আপনি কী করতে চান?', dashChooseMode: 'আপনার কাজের মোড বেছে নিন',
    dashEmptyHint: '✨ এখনও কোনো প্রকল্প নেই — শুরু করতে নিচের একটি মোড বেছে নিন (বিনামূল্যে ও সীমাহীন)।',
    dashWizard: 'গাইডেড উইজার্ড', dashWizardDesc: 'সহজ প্রশ্নের সাথে ধাপে ধাপে আপনার অ্যাপ তৈরি করুন',
    dashChat: 'চ্যাট', dashChatBadgeOn: 'অনলাইন AI', dashChatDescOn: 'শক্তিশালী AI-এর সাথে কথা বলুন',
    dashChatBadgeOff: 'অফলাইন AI', dashChatDescOff: 'ইন্টারনেট ছাড়াই স্থানীয় AI (Ollama)',
    dashCreate: 'তৈরি করুন', dashCreateBadgeOn: 'অনলাইন', dashCreateDescOn: 'মোবাইল, ওয়েব, ডেস্কটপ অ্যাপ তৈরি করুন',
    dashCreateBadgeOff: 'অফলাইন', dashCreateDescOff: 'স্থানীয় AI (Ollama) দিয়ে অ্যাপ তৈরি করুন',
    dashInfoOnline: '💡 অনলাইন মোড: রিমোট Ollama সহ শক্তিশালী AI',
    dashInfoOffline: '🔌 অফলাইন মোড: স্থানীয়ভাবে Ollama ইনস্টল থাকা প্রয়োজন',
    dashCollapseSidebar: 'সাইডবার লুকান', dashExpandSidebar: 'প্রকল্প দেখান',
  },

  // ========== Português ==========
  pt: {
    back: 'Voltar', next: 'Seguinte', previous: 'Anterior', generate: 'Gerar',
    loading: 'A carregar…', error: 'Erro', success: 'Sucesso', cancel: 'Cancelar',
    save: 'Guardar', delete: 'Eliminar', edit: 'Editar', close: 'Fechar', yes: 'Sim', no: 'Não',
    loginSignin: 'Entrar', loginSignup: 'Registar',
    loginConnectToContinue: 'Inicia sessão para continuar',
    loginCreateAccount: 'Cria a tua conta gratuita',
    loginEmail: 'Endereço de e-mail (Gmail recomendado)',
    loginPassword: 'Palavra-passe', loginName: 'Nome (opcional)',
    loginSubmitSignin: 'Entrar', loginSubmitSignup: 'Criar conta',
    loginMagicLink: 'Entrar por link mágico (sem palavra-passe)',
    loginForgot: 'Esqueceste a palavra-passe?',
    loginSmsDemo: 'Entrar por SMS (demonstração)',
    loginOrOffline: 'ou modo offline',
    loginBackHome: '← Voltar ao início',
    loginHowItWorks: 'Como funciona', loginLegal: 'Termos e Privacidade',
    loginWaitingForConfirm: 'A aguardar confirmação…',
    loginEmailMinChars: 'Mínimo de 6 caracteres', loginExpiresIn: 'Expira em',
    loginResendBtn: 'Reenviar link', loginResendSent: 'A enviar…',
    loginResendCooldown: 'Aguarda 10 min',
    loginIdleNotice: 'Foste desconectado após 1h ou mais de inatividade. Fecha esta mensagem e inicia sessão novamente.',
    dashProjects: 'Projetos', dashNewProject: 'Novo projeto', dashSwitchAccount: 'Mudar de conta', dashLogout: 'Terminar sessão',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'IA disponível',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Criação sem limites',
    dashWhatToDo: 'O que queres fazer?', dashChooseMode: 'Escolhe o teu modo de trabalho',
    dashEmptyHint: '✨ Ainda sem projetos — escolhe um modo abaixo para começar (gratuito e ilimitado).',
    dashWizard: 'Assistente guiado', dashWizardDesc: 'Cria a tua app passo a passo com perguntas simples',
    dashChat: 'Conversa', dashChatBadgeOn: 'IA ONLINE', dashChatDescOn: 'Conversa com uma IA poderosa',
    dashChatBadgeOff: 'IA OFFLINE', dashChatDescOff: 'IA local (Ollama) sem internet',
    dashCreate: 'Criar', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Gera apps móvel, web, desktop',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Gera apps com IA local (Ollama)',
    dashInfoOnline: '💡 Modo online: IA poderosa com Ollama remoto',
    dashInfoOffline: '🔌 Modo offline: requer Ollama instalado localmente',
    dashCollapseSidebar: 'Recolher barra', dashExpandSidebar: 'Mostrar projetos',
  },

  // ========== اردو (Urdu) — RTL ==========
  ur: {
    back: 'واپس', next: 'اگلا', previous: 'پچھلا', generate: 'بنائیں',
    loading: 'لوڈ ہو رہا ہے…', error: 'خرابی', success: 'کامیابی', cancel: 'منسوخ کریں',
    save: 'محفوظ کریں', delete: 'حذف کریں', edit: 'ترمیم', close: 'بند کریں', yes: 'ہاں', no: 'نہیں',
    loginSignin: 'سائن ان', loginSignup: 'سائن اپ',
    loginConnectToContinue: 'جاری رکھنے کے لیے سائن ان کریں',
    loginCreateAccount: 'اپنا مفت اکاؤنٹ بنائیں',
    loginEmail: 'ای میل پتہ (Gmail ترجیحی)',
    loginPassword: 'پاس ورڈ', loginName: 'نام (اختیاری)',
    loginSubmitSignin: 'سائن ان', loginSubmitSignup: 'اکاؤنٹ بنائیں',
    loginMagicLink: 'میجک لنک سائن ان (بغیر پاس ورڈ)',
    loginForgot: 'پاس ورڈ بھول گئے؟',
    loginSmsDemo: 'SMS سائن ان (ڈیمو)',
    loginOrOffline: 'یا آف لائن موڈ',
    loginBackHome: '← ہوم پر واپس',
    loginHowItWorks: 'یہ کیسے کام کرتا ہے', loginLegal: 'شرائط و رازداری',
    loginWaitingForConfirm: 'تصدیق کا انتظار…',
    loginEmailMinChars: 'کم از کم 6 حروف', loginExpiresIn: 'ختم ہونے میں',
    loginResendBtn: 'لنک دوبارہ بھیجیں', loginResendSent: 'بھیجا جا رہا ہے…',
    loginResendCooldown: '10 منٹ انتظار کریں',
    loginIdleNotice: '1 گھنٹے یا زیادہ غیر فعال رہنے کے بعد آپ کو لاگ آؤٹ کر دیا گیا ہے۔ یہ پیغام بند کریں اور دوبارہ سائن ان کریں۔',
    dashProjects: 'پراجیکٹس', dashNewProject: 'نیا پراجیکٹ', dashSwitchAccount: 'اکاؤنٹ تبدیل کریں', dashLogout: 'لاگ آؤٹ',
    dashOnline: 'آن لائن', dashOffline: 'آف لائن', dashAiAvailable: 'AI دستیاب',
    dashTitle: 'CodeForge AI', dashSubtitle: 'لامحدود تخلیق',
    dashWhatToDo: 'آپ کیا کرنا چاہتے ہیں؟', dashChooseMode: 'اپنا کام کا موڈ منتخب کریں',
    dashEmptyHint: '✨ ابھی کوئی پراجیکٹ نہیں — شروع کرنے کے لیے نیچے ایک موڈ منتخب کریں (مفت اور لامحدود)۔',
    dashWizard: 'گائیڈڈ وزرڈ', dashWizardDesc: 'سادہ سوالات کے ساتھ مرحلہ وار اپنی ایپ بنائیں',
    dashChat: 'گفتگو', dashChatBadgeOn: 'آن لائن AI', dashChatDescOn: 'طاقتور AI سے بات چیت کریں',
    dashChatBadgeOff: 'آف لائن AI', dashChatDescOff: 'انٹرنیٹ کے بغیر مقامی AI (Ollama)',
    dashCreate: 'بنائیں', dashCreateBadgeOn: 'آن لائن', dashCreateDescOn: 'موبائل، ویب، ڈیسک ٹاپ ایپس بنائیں',
    dashCreateBadgeOff: 'آف لائن', dashCreateDescOff: 'مقامی AI (Ollama) سے ایپس بنائیں',
    dashInfoOnline: '💡 آن لائن موڈ: ریموٹ Ollama کے ساتھ طاقتور AI',
    dashInfoOffline: '🔌 آف لائن موڈ: مقامی طور پر Ollama انسٹال ہونا ضروری',
    dashCollapseSidebar: 'سائڈ بار چھپائیں', dashExpandSidebar: 'پراجیکٹس دکھائیں',
  }
};

// Supported languages — used by the dropdown selector.
// `label` = name in its own (native) language. `flag` = emoji flag for visual cue.
export const SUPPORTED_LANGS = [
  { code: 'fr', label: 'Français', native: 'FR', flag: '🇫🇷' },
  { code: 'en', label: 'English', native: 'EN', flag: '🇬🇧' },
  { code: 'es', label: 'Español', native: 'ES', flag: '🇪🇸' },
  { code: 'pt', label: 'Português', native: 'PT', flag: '🇵🇹' },
  { code: 'de', label: 'Deutsch', native: 'DE', flag: '🇩🇪' },
  { code: 'nl', label: 'Nederlands', native: 'NL', flag: '🇳🇱' },
  { code: 'ru', label: 'Русский', native: 'RU', flag: '🇷🇺' },
  { code: 'zh', label: '中文 (简体)', native: '中文', flag: '🇨🇳' },
  { code: 'zh-TW', label: '中文 (繁體)', native: '繁體', flag: '🇹🇼' },
  { code: 'hi', label: 'हिन्दी', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', label: 'বাংলা', native: 'বাংলা', flag: '🇧🇩' },
  { code: 'ur', label: 'اردو', native: 'اردو', flag: '🇵🇰' },
];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('codeforge_language');
    if (saved && translations[saved]) return saved;

    const supported = Object.keys(translations);
    const full = (navigator.language || 'en').toLowerCase();
    // Try full code first (e.g. zh-TW), then primary tag (e.g. zh)
    if (supported.includes(full)) return full;
    const primary = full.split('-')[0];
    const exact = supported.find(c => c.toLowerCase() === primary || c.toLowerCase().startsWith(primary + '-'));
    return exact || 'en';
  });

  useEffect(() => {
    localStorage.setItem('codeforge_language', language);
    // Apply RTL direction for Right-to-Left scripts (Urdu, Arabic, Hebrew…)
    try {
      const RTL_LANGS = ['ur', 'ar', 'he', 'fa'];
      const dir = RTL_LANGS.includes(language) ? 'rtl' : 'ltr';
      document.documentElement.setAttribute('dir', dir);
      document.documentElement.setAttribute('lang', language);
    } catch (_) {}
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  // Kept for backwards compatibility — cycles through supported languages.
  const toggleLanguage = () => {
    setLanguage(prev => {
      const codes = Object.keys(translations);
      const idx = codes.indexOf(prev);
      return codes[(idx + 1) % codes.length];
    });
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
