import React, { createContext, useContext, useState, useEffect } from 'react';

// Traductions
const translations = {
  fr: {
    // Common
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    generate: 'Générer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',

    // Login page
    loginSignin: 'Connexion',
    loginSignup: 'Inscription',
    loginConnectToContinue: 'Connecte-toi pour continuer',
    loginCreateAccount: 'Crée ton compte gratuit',
    loginEmail: 'Adresse email (Gmail de préférence)',
    loginPassword: 'Mot de passe',
    loginName: 'Nom (optionnel)',
    loginSubmitSignin: 'Se connecter',
    loginSubmitSignup: 'Créer mon compte',
    loginMagicLink: 'Connexion par lien magique (sans mot de passe)',
    loginForgot: 'Mot de passe oublié ?',
    loginSmsDemo: 'Connexion SMS (démo)',
    loginOrOffline: 'ou mode hors-ligne',
    loginBackHome: "← Retour à l'accueil",
    loginHowItWorks: 'Comment ça marche',
    loginLegal: 'CGU & Confidentialité',
    loginWaitingForConfirm: 'En attente de la confirmation…',
    loginEmailMinChars: '6 caractères minimum',
    loginExpiresIn: 'Expire dans',
    loginResendBtn: 'Renvoyer le lien',
    loginResendSent: 'Envoi…',
    loginResendCooldown: 'Patiente 10 min',
    loginIdleNotice: "Vous avez été déconnecté après 1h ou plus d'inactivité. Vous pouvez fermer ce message et vous reconnecter.",

    // Auth (legacy)
    login: 'Connexion',
    logout: 'Déconnexion',
    loginWithGoogle: 'Continuer avec Google',
    loginWithSMS: 'Connexion SMS (Hors Ligne)',
    phoneNumber: 'Numéro de téléphone',
    sendCode: 'Envoyer le code',
    verifyCode: 'Vérifier le code',
    invalidCode: 'Code invalide',
    codeSent: 'Code envoyé !',
    
    // Dashboard
    dashboard: 'Tableau de bord',
    projects: 'Projets',
    newProject: 'Nouveau Projet',
    whatToDo: 'Que souhaitez-vous faire ?',
    chooseWorkMode: 'Choisissez votre mode de travail',
    
    // Modes
    online: 'En ligne',
    offline: 'Hors ligne',
    onlineChat: 'Interaction IA en ligne',
    offlineChat: 'Interaction IA hors ligne',
    onlineCreate: 'Création en ligne',
    offlineCreate: 'Création hors ligne',
    
    // Create
    createTitle: 'Création IA Sans Limites',
    describeApp: 'Décrivez votre application',
    aiGeneratesAll: "L'IA génère tout automatiquement",
    unlimitedCreation: 'Création Illimitée',
    describeWhatYouWant: 'Décrivez ce que vous voulez créer',
    generationInProgress: 'Génération en cours...',
    appGenerated: 'Application générée !',
    codeReadyExport: 'Code généré et prêt à exporter',
    
    // Preview
    preview: 'Prévisualisation',
    previewWeb: 'Prévisualiser Web',
    previewApp: 'Prévisualiser App',
    previewPDF: 'Prévisualiser PDF',
    previewDOCX: 'Prévisualiser DOCX',
    
    // Export
    export: 'Export',
    exportAPK: 'Export Mobile (APK)',
    exportEXE: 'Export Desktop (EXE)',
    exportWeb: 'Déploiement Web',
    downloadSource: 'Télécharger le code source',
    installOnAndroid: 'Installez sur Android directement',
    downloadInstaller: "Téléchargez l'installateur Windows",
    deployVercel: 'Déployez sur Vercel, Netlify ou votre hébergeur',
    
    // Wizard
    wizardTitle: 'Assistant de Création',
    step: 'Étape',
    whatTypeApp: "Quel type d'application ?",
    chooseTemplate: 'Choisissez le modèle qui correspond le mieux',
    giveName: 'Donnez un nom',
    whatWillBeCalled: "Comment s'appellera votre application ?",
    chooseColors: 'Choisissez vos couleurs',
    selectPalette: 'Sélectionnez une palette de couleurs',
    targetPlatform: 'Plateforme cible',
    whereUsed: 'Où sera utilisée votre application ?',
    advancedOptions: 'Options avancées',
    customizeFeatures: 'Personnalisez les fonctionnalités',
    authentication: 'Authentification',
    loginSignupSystem: 'Système de login/signup',
    database: 'Base de données',
    persistentStorage: 'Stockage de données persistant',
    interfaceLanguage: "Langue de l'interface",
    summary: 'Résumé de votre application',
    generateApp: "Générer l'Application",
    appReady: 'Application prête à être exportée',
    
    // App Types
    ecommerce: 'E-Commerce',
    blog: 'Blog/CMS',
    social: 'Réseau Social',
    chat: 'Messagerie',
    portfolio: 'Portfolio',
    dashboardType: 'Dashboard',
    booking: 'Réservation',
    media: 'Média/Streaming',
    maps: 'Géolocalisation',
    utility: 'Utilitaire',
    music: 'Audio/Musique',
    custom: 'Personnalisé',
    
    // Platforms
    web: 'Web',
    mobile: 'Mobile',
    desktop: 'Desktop',
    allPlatforms: 'Toutes',

    // Dashboard
    dashProjects: 'Projets',
    dashNewProject: 'Nouveau Projet',
    dashSwitchAccount: 'Changer de compte',
    dashLogout: 'Déconnexion',
    dashOnline: 'En ligne',
    dashOffline: 'Hors ligne',
    dashAiAvailable: 'IA Disponible',
    dashTitle: 'CodeForge AI',
    dashSubtitle: 'Création Sans Limites',
    dashWhatToDo: 'Que souhaitez-vous faire ?',
    dashChooseMode: 'Choisissez votre mode de travail',
    dashEmptyHint: "✨ Aucun projet pour l'instant — choisis un mode ci-dessous pour commencer (tout est gratuit et sans limites).",
    dashWizard: 'Assistant Guidé',
    dashWizardDesc: 'Créez votre projet étape par étape avec des questions simples',
    dashChat: 'Interaction',
    dashChatBadgeOn: 'IA EN LIGNE',
    dashChatDescOn: 'Discutez avec une IA puissante',
    dashChatBadgeOff: 'IA HORS LIGNE',
    dashChatDescOff: 'IA locale (Ollama) sans connexion',
    dashCreate: 'Création',
    dashCreateBadgeOn: 'EN LIGNE',
    dashCreateDescOn: 'Générez apps mobile, web, desktop',
    dashCreateBadgeOff: 'HORS LIGNE',
    dashCreateDescOff: 'Générez apps avec IA locale (Ollama)',
    dashInfoOnline: '💡 Mode en ligne : IA puissante avec Ollama distant',
    dashInfoOffline: '🔌 Mode hors ligne : Nécessite Ollama installé localement',
    dashCollapseSidebar: 'Réduire la barre',
    dashExpandSidebar: 'Afficher les projets',
    dashTutorial: 'Tutoriel',

    // Landing page
    l_navDiscover: 'Découvrir',
    l_h1Line1: 'Créez des Applications',
    l_h1Highlight: 'Applications',
    l_h1Line2: 'Sans Écrire de Code',
    l_subtitle: "Décrivez votre projet, notre IA génère instantanément le code complet. Applications web, mobile et desktop. Sans limites. 100% gratuit.",
    l_signupBtn: 'Inscription',
    l_loginBtn: 'Connexion',
    l_statUnlimited: 'Génération Illimitée',
    l_statAI: 'IA de Pointe',
    l_statFormats: 'Web, Mobile, Desktop',
    l_featTitle: 'Une Plateforme Révolutionnaire',
    l_featTitleHighlight: 'Révolutionnaire',
    l_feat1T: 'Génération Intelligente',
    l_feat1D: "Notre IA analyse votre description et génère du code professionnel instantanément.",
    l_feat2T: 'Apps Mobile (.apk)',
    l_feat2D: 'Exportez directement vers Android. Installation en un clic sur votre téléphone.',
    l_feat3T: 'Logiciels Desktop (.exe)',
    l_feat3D: 'Créez des applications Windows professionnelles prêtes à distribuer.',
    l_feat4T: 'Sites Web',
    l_feat4D: 'Déployez instantanément sur le web avec un hébergement intégré.',
    l_feat5T: 'Mode Hors Ligne',
    l_feat5D: 'Continuez à créer même sans connexion. Basculement automatique.',
    l_feat6T: 'Sans Restrictions',
    l_feat6D: "Aucune limite d'utilisation. Aucun crédit. Créativité totale.",
    l_ctaTitle: 'Prêt à Créer Sans Limites ?',
    l_ctaSub: "Rejoins la révolution du développement assisté par IA.",
    l_ctaBtn: 'Démarrer Maintenant',
    l_footer: '© 2026 CodeForge AI. Propulsé par Emergent AI. Sans restrictions, sans limites.',

    // Discover (tutorial) page
    d_exit: 'Quitter la visite',
    d_step: 'Étape',
    d_login: 'Connexion',
    d_prev: 'Précédent',
    d_next: 'Suivant',
    d_signup: "S'inscrire",
    d_kbTip: 'Astuce : utilise les flèches ← → du clavier pour naviguer.',
    d_locked: '🔒 Connecte-toi pour utiliser cette fonctionnalité.',
    d_preview: 'aperçu',
    d_t1: 'Bienvenue dans CodeForge AI',
    d_b1: "Voici ton futur tableau de bord. Avance avec les flèches pour découvrir chaque écran. Tu pourras tout utiliser après inscription.",
    d_t2: '1️⃣ Assistant Guidé (Wizard)',
    d_b2: "L'IA te pose 4 à 5 questions simples (type d'app, nom, couleurs, plateforme) et génère le projet complet. Idéal si tu n'as pas d'idée précise.",
    d_t3: '2️⃣ Création libre',
    d_b3: "Décris ton app en une phrase comme « un site de recettes avec note 5 étoiles ». L'IA génère le code complet en moins d'une minute.",
    d_t4: "3️⃣ Chat avec l'IA",
    d_b4: "Une fois ton app générée, demande des modifications en langage naturel : « ajoute un dark mode », « change le bouton en vert ». 🎙️ Deux micros sont disponibles : un envoie un message vocal directement (point rouge), l'autre transcrit ta voix dans le champ texte pour relire avant d'envoyer.",
    d_t5: '4️⃣ Aperçu instantané',
    d_b5: "Vois ton app tourner immédiatement, comme si elle était déjà déployée. Web, mobile (PWA) ou desktop — au choix.",
    d_t6: '5️⃣ Mode Hors-Ligne',
    d_b6: "Pas de connexion ? Avec Ollama installé sur ton PC, tu génères des apps sans envoyer aucune donnée à Internet. 100% privé, 100% gratuit.",
    d_t7: 'Prêt·e à essayer ?',
    d_b7: "Crée ton compte en 30 secondes — il te suffit d'un email et d'un mot de passe. Pas de CB, pas de pub, pas de quotas.",

    // Voice / microphones (Chat & Create input)
    mic_voice_send: 'Message vocal — parler & envoyer',
    mic_voice_text: 'Voix vers texte — parler & relire',
    mic_unsupported: '🎤 Le micro n\'est pas disponible sur ce navigateur.',
    mic_permission: '🎤 Autorise l\'accès au micro pour utiliser cette fonction.',
    mic_too_short: '🎤 Enregistrement trop court — réessaie.',
    mic_no_text: '🎤 Aucun texte reconnu — parle plus clairement.',
    mic_failed: '🎤 Échec de la transcription. Réessaie.',
    mic_voice_badge: 'Vocal',

    // Attachments (paperclip)
    attach_title: 'Joindre',
    attach_device: 'Depuis l\'appareil',
    attach_device_sub: 'Sélectionne un fichier sur ton appareil',
    attach_clipboard: 'Depuis le presse-papier',
    attach_clipboard_sub: 'Colle ce que tu viens de copier',
    attach_url: 'Depuis une URL',
    attach_url_sub: 'Colle un lien vers une image ou un fichier',
    attach_clip_empty: '📋 Le presse-papier est vide.',
    attach_clip_fail: '📋 Impossible de lire le presse-papier (autorisation requise).',
    attach_url_invalid: '🔗 URL invalide. Vérifie le format.',
    attach_attached: 'Pièce jointe ajoutée',
    cancel: 'Annuler',
    sidebar_my_profile: 'Mon profil',
    login_password_wrong: 'Mot de passe incorrect',
    login_email_unknown: 'Aucun compte avec cet email'
  },
  
  en: {
    // Common
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    generate: 'Generate',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    yes: 'Yes',
    no: 'No',

    // Login page
    loginSignin: 'Sign in',
    loginSignup: 'Sign up',
    loginConnectToContinue: 'Sign in to continue',
    loginCreateAccount: 'Create your free account',
    loginEmail: 'Email address (Gmail preferred)',
    loginPassword: 'Password',
    loginName: 'Name (optional)',
    loginSubmitSignin: 'Sign in',
    loginSubmitSignup: 'Create my account',
    loginMagicLink: 'Magic link sign-in (no password)',
    loginForgot: 'Forgot your password?',
    loginSmsDemo: 'SMS sign-in (demo)',
    loginOrOffline: 'or offline mode',
    loginBackHome: '← Back to home',
    loginHowItWorks: 'How it works',
    loginLegal: 'Terms & Privacy',
    loginWaitingForConfirm: 'Waiting for confirmation…',
    loginEmailMinChars: '6 characters minimum',
    loginExpiresIn: 'Expires in',
    loginResendBtn: 'Resend link',
    loginResendSent: 'Sending…',
    loginResendCooldown: 'Wait 10 min',
    loginIdleNotice: "You were logged out after 1h+ of inactivity. Close this message and sign in again.",
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    
    // Auth
    login: 'Login',
    logout: 'Logout',
    loginWithGoogle: 'Continue with Google',
    loginWithSMS: 'SMS Login (Offline)',
    phoneNumber: 'Phone number',
    sendCode: 'Send code',
    verifyCode: 'Verify code',
    invalidCode: 'Invalid code',
    codeSent: 'Code sent!',
    
    // Dashboard
    dashboard: 'Dashboard',
    projects: 'Projects',
    newProject: 'New Project',
    whatToDo: 'What would you like to do?',
    chooseWorkMode: 'Choose your work mode',
    
    // Modes
    online: 'Online',
    offline: 'Offline',
    onlineChat: 'Online AI Chat',
    offlineChat: 'Offline AI Chat',
    onlineCreate: 'Online Creation',
    offlineCreate: 'Offline Creation',
    
    // Create
    createTitle: 'Unlimited AI Creation',
    describeApp: 'Describe your application',
    aiGeneratesAll: 'AI generates everything automatically',
    unlimitedCreation: 'Unlimited Creation',
    describeWhatYouWant: 'Describe what you want to create',
    generationInProgress: 'Generation in progress...',
    appGenerated: 'Application generated!',
    codeReadyExport: 'Code generated and ready to export',
    
    // Preview
    preview: 'Preview',
    previewWeb: 'Preview Web',
    previewApp: 'Preview App',
    previewPDF: 'Preview PDF',
    previewDOCX: 'Preview DOCX',
    
    // Export
    export: 'Export',
    exportAPK: 'Mobile Export (APK)',
    exportEXE: 'Desktop Export (EXE)',
    exportWeb: 'Web Deployment',
    downloadSource: 'Download source code',
    installOnAndroid: 'Install on Android directly',
    downloadInstaller: 'Download Windows installer',
    deployVercel: 'Deploy on Vercel, Netlify or your host',
    
    // Wizard
    wizardTitle: 'Creation Wizard',
    step: 'Step',
    whatTypeApp: 'What type of application?',
    chooseTemplate: 'Choose the template that fits best',
    giveName: 'Give it a name',
    whatWillBeCalled: 'What will your application be called?',
    chooseColors: 'Choose your colors',
    selectPalette: 'Select a color palette',
    targetPlatform: 'Target platform',
    whereUsed: 'Where will your application be used?',
    advancedOptions: 'Advanced options',
    customizeFeatures: 'Customize features',
    authentication: 'Authentication',
    loginSignupSystem: 'Login/signup system',
    database: 'Database',
    persistentStorage: 'Persistent data storage',
    interfaceLanguage: 'Interface language',
    summary: 'Your application summary',
    generateApp: 'Generate Application',
    appReady: 'Application ready to export',
    
    // App Types
    ecommerce: 'E-Commerce',
    blog: 'Blog/CMS',
    social: 'Social Network',
    chat: 'Messaging',
    portfolio: 'Portfolio',
    dashboardType: 'Dashboard',
    booking: 'Booking',
    media: 'Media/Streaming',
    maps: 'Geolocation',
    utility: 'Utility',
    music: 'Audio/Music',
    custom: 'Custom',
    
    // Platforms
    web: 'Web',
    mobile: 'Mobile',
    desktop: 'Desktop',
    allPlatforms: 'All',

    // Dashboard
    dashProjects: 'Projects',
    dashNewProject: 'New Project',
    dashSwitchAccount: 'Switch account',
    dashLogout: 'Sign out',
    dashOnline: 'Online',
    dashOffline: 'Offline',
    dashAiAvailable: 'AI available',
    dashTitle: 'CodeForge AI',
    dashSubtitle: 'Unlimited Creation',
    dashWhatToDo: 'What would you like to do?',
    dashChooseMode: 'Choose your work mode',
    dashEmptyHint: '✨ No projects yet — pick a mode below to get started (free and unlimited).',
    dashWizard: 'Guided Wizard',
    dashWizardDesc: 'Create your project step by step with simple questions',
    dashChat: 'Chat',
    dashChatBadgeOn: 'ONLINE AI',
    dashChatDescOn: 'Chat with a powerful AI',
    dashChatBadgeOff: 'OFFLINE AI',
    dashChatDescOff: 'Local AI (Ollama) without internet',
    dashCreate: 'Create',
    dashCreateBadgeOn: 'ONLINE',
    dashCreateDescOn: 'Generate mobile, web, desktop apps',
    dashCreateBadgeOff: 'OFFLINE',
    dashCreateDescOff: 'Generate apps with local AI (Ollama)',
    dashInfoOnline: '💡 Online mode: Powerful AI with remote Ollama',
    dashInfoOffline: '🔌 Offline mode: Requires Ollama installed locally',
    dashCollapseSidebar: 'Collapse sidebar',
    dashExpandSidebar: 'Show projects',
    dashTutorial: 'Tutorial',

    // Landing page
    l_navDiscover: 'Discover',
    l_h1Line1: 'Build Applications',
    l_h1Highlight: 'Applications',
    l_h1Line2: 'Without Writing Code',
    l_subtitle: "Describe your project, our AI instantly generates the complete code. Web, mobile and desktop apps. No limits. 100% free.",
    l_signupBtn: 'Sign up',
    l_loginBtn: 'Sign in',
    l_statUnlimited: 'Unlimited Generation',
    l_statAI: 'Cutting-edge AI',
    l_statFormats: 'Web, Mobile, Desktop',
    l_featTitle: 'A Revolutionary Platform',
    l_featTitleHighlight: 'Revolutionary',
    l_feat1T: 'Smart Generation',
    l_feat1D: 'Our AI analyzes your description and generates professional code instantly.',
    l_feat2T: 'Mobile Apps (.apk)',
    l_feat2D: 'Export directly to Android. One-click install on your phone.',
    l_feat3T: 'Desktop Software (.exe)',
    l_feat3D: 'Build professional Windows applications ready to ship.',
    l_feat4T: 'Websites',
    l_feat4D: 'Deploy to the web instantly with integrated hosting.',
    l_feat5T: 'Offline Mode',
    l_feat5D: 'Keep building even without internet. Automatic fallback.',
    l_feat6T: 'No Restrictions',
    l_feat6D: 'No usage limits. No credits. Total creativity.',
    l_ctaTitle: 'Ready to Build Without Limits?',
    l_ctaSub: 'Join the AI-assisted development revolution.',
    l_ctaBtn: 'Start Now',
    l_footer: '© 2026 CodeForge AI. Powered by Emergent AI. No restrictions, no limits.',

    // Discover (tutorial) page
    d_exit: 'Exit tour',
    d_step: 'Step',
    d_login: 'Sign in',
    d_prev: 'Previous',
    d_next: 'Next',
    d_signup: 'Sign up',
    d_kbTip: 'Tip: use the ← → arrow keys to navigate.',
    d_locked: '🔒 Sign in to use this feature.',
    d_preview: 'preview',
    d_t1: 'Welcome to CodeForge AI',
    d_b1: "Here's your future dashboard. Use the arrows to explore each screen. You'll be able to use everything after signing up.",
    d_t2: '1️⃣ Guided Wizard',
    d_b2: "The AI asks 4-5 simple questions (app type, name, colors, platform) and generates the full project. Perfect if you don't have a clear idea.",
    d_t3: '2️⃣ Free creation',
    d_b3: 'Describe your app in one sentence like "a recipe site with 5-star ratings". The AI generates the full code in under a minute.',
    d_t4: '3️⃣ Chat with the AI',
    d_b4: 'Once generated, request changes in plain English: "add dark mode", "make the button green". 🎙️ Two mics are available: one sends a voice message instantly (red dot), the other transcribes your speech into the text field so you can review before sending.',
    d_t5: '4️⃣ Instant preview',
    d_b5: 'See your app running immediately, as if already deployed. Web, mobile (PWA) or desktop — your choice.',
    d_t6: '5️⃣ Offline Mode',
    d_b6: "No internet? With Ollama on your PC, generate apps without sending any data online. 100% private, 100% free.",
    d_t7: 'Ready to try?',
    d_b7: "Create your account in 30 seconds — just an email and a password. No card, no ads, no quotas.",

    // Voice / microphones
    mic_voice_send: 'Voice message — speak & send',
    mic_voice_text: 'Voice to text — speak & review',
    mic_unsupported: '🎤 Microphone not supported in this browser.',
    mic_permission: '🎤 Please allow microphone access to use this feature.',
    mic_too_short: '🎤 Recording too short — try again.',
    mic_no_text: '🎤 No speech detected — speak more clearly.',
    mic_failed: '🎤 Transcription failed. Please try again.',
    mic_voice_badge: 'Voice',

    // Attachments
    attach_title: 'Attach',
    attach_device: 'From device',
    attach_device_sub: 'Pick a file from your device',
    attach_clipboard: 'From clipboard',
    attach_clipboard_sub: 'Paste what you just copied',
    attach_url: 'From URL',
    attach_url_sub: 'Paste a link to an image or file',
    attach_clip_empty: '📋 Clipboard is empty.',
    attach_clip_fail: '📋 Unable to read clipboard (permission required).',
    attach_url_invalid: '🔗 Invalid URL. Check the format.',
    attach_attached: 'Attachment added',
    cancel: 'Cancel',
    sidebar_my_profile: 'My profile',
    login_password_wrong: 'Incorrect password',
    login_email_unknown: 'No account with this email'
  },

  // ========== ESPAÑOL ==========
  es: {
    back: 'Volver', next: 'Siguiente', previous: 'Anterior', generate: 'Generar',
    loading: 'Cargando…', error: 'Error', success: 'Éxito', cancel: 'Cancelar',
    save: 'Guardar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar', yes: 'Sí', no: 'No',
    loginSignin: 'Iniciar sesión', loginSignup: 'Registrarse',
    loginConnectToContinue: 'Inicia sesión para continuar',
    loginCreateAccount: 'Crea tu cuenta gratuita',
    loginEmail: 'Correo electrónico (Gmail preferido)',
    loginPassword: 'Contraseña', loginName: 'Nombre (opcional)',
    loginSubmitSignin: 'Iniciar sesión', loginSubmitSignup: 'Crear mi cuenta',
    loginMagicLink: 'Acceso por enlace mágico (sin contraseña)',
    loginForgot: '¿Olvidaste tu contraseña?',
    loginSmsDemo: 'Acceso por SMS (demo)',
    loginOrOffline: 'o modo sin conexión',
    loginBackHome: '← Volver al inicio',
    loginHowItWorks: 'Cómo funciona', loginLegal: 'Términos y Privacidad',
    loginWaitingForConfirm: 'Esperando confirmación…',
    loginEmailMinChars: '6 caracteres mínimo', loginExpiresIn: 'Expira en',
    loginResendBtn: 'Reenviar enlace', loginResendSent: 'Enviando…',
    loginResendCooldown: 'Espera 10 min',
    loginIdleNotice: 'Has sido desconectado tras 1 h o más de inactividad. Cierra este mensaje y vuelve a iniciar sesión.',
    dashProjects: 'Proyectos', dashNewProject: 'Nuevo proyecto', dashSwitchAccount: 'Cambiar de cuenta', dashLogout: 'Cerrar sesión',
    dashOnline: 'En línea', dashOffline: 'Sin conexión', dashAiAvailable: 'IA disponible',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Creación sin límites',
    dashWhatToDo: '¿Qué quieres hacer?', dashChooseMode: 'Elige tu modo de trabajo',
    dashEmptyHint: '✨ Aún no hay proyectos — elige un modo para empezar (gratis e ilimitado).',
    dashWizard: 'Asistente guiado', dashWizardDesc: 'Crea tu app paso a paso con preguntas sencillas',
    dashChat: 'Interacción', dashChatBadgeOn: 'IA EN LÍNEA', dashChatDescOn: 'Chatea con una IA potente',
    dashChatBadgeOff: 'IA SIN CONEXIÓN', dashChatDescOff: 'IA local (Ollama) sin internet',
    dashCreate: 'Crear', dashCreateBadgeOn: 'EN LÍNEA', dashCreateDescOn: 'Genera apps móvil, web, desktop',
    dashCreateBadgeOff: 'SIN CONEXIÓN', dashCreateDescOff: 'Genera apps con IA local (Ollama)',
    dashInfoOnline: '💡 Modo en línea: IA potente con Ollama remoto',
    dashInfoOffline: '🔌 Modo sin conexión: requiere Ollama instalado localmente',
    dashCollapseSidebar: 'Ocultar barra', dashExpandSidebar: 'Mostrar proyectos', dashTutorial: 'Tutorial',
    l_navDiscover: 'Descubrir', l_h1Line1: 'Crea Aplicaciones', l_h1Highlight: 'Aplicaciones', l_h1Line2: 'Sin Escribir Código',
    l_subtitle: 'Describe tu proyecto, nuestra IA genera al instante el código completo. Apps web, móvil y escritorio. Sin límites. 100% gratis.',
    l_signupBtn: 'Registrarse', l_loginBtn: 'Iniciar sesión',
    l_statUnlimited: 'Generación Ilimitada', l_statAI: 'IA de Vanguardia', l_statFormats: 'Web, Móvil, Escritorio',
    l_featTitle: 'Una Plataforma Revolucionaria', l_featTitleHighlight: 'Revolucionaria',
    l_feat1T: 'Generación Inteligente', l_feat1D: 'Nuestra IA analiza tu descripción y genera código profesional al instante.',
    l_feat2T: 'Apps Móvil (.apk)', l_feat2D: 'Exporta directamente a Android. Instalación en un clic.',
    l_feat3T: 'Software Escritorio (.exe)', l_feat3D: 'Crea aplicaciones Windows profesionales listas para distribuir.',
    l_feat4T: 'Sitios Web', l_feat4D: 'Despliega al instante en la web con hosting integrado.',
    l_feat5T: 'Modo Sin Conexión', l_feat5D: 'Sigue creando incluso sin internet. Cambio automático.',
    l_feat6T: 'Sin Restricciones', l_feat6D: 'Sin límites de uso. Sin créditos. Creatividad total.',
    l_ctaTitle: '¿Listo para Crear Sin Límites?', l_ctaSub: 'Únete a la revolución del desarrollo con IA.',
    l_ctaBtn: 'Empezar Ahora',
    l_footer: '© 2026 CodeForge AI. Impulsado por Emergent AI. Sin restricciones, sin límites.',
    d_exit: 'Salir de la visita', d_step: 'Paso', d_login: 'Iniciar sesión',
    d_prev: 'Anterior', d_next: 'Siguiente', d_signup: 'Registrarse',
    d_kbTip: 'Consejo: usa las flechas ← → del teclado para navegar.',
    d_locked: '🔒 Inicia sesión para usar esta función.', d_preview: 'vista previa',
    d_t1: 'Bienvenido a CodeForge AI',
    d_b1: 'Aquí está tu futuro panel. Avanza con las flechas para explorar cada pantalla. Podrás usar todo después de registrarte.',
    d_t2: '1️⃣ Asistente Guiado',
    d_b2: 'La IA te hace 4-5 preguntas simples (tipo de app, nombre, colores, plataforma) y genera el proyecto completo.',
    d_t3: '2️⃣ Creación libre',
    d_b3: 'Describe tu app en una frase: «un sitio de recetas con valoración de 5 estrellas». La IA genera el código en menos de un minuto.',
    d_t4: '3️⃣ Chat con la IA',
    d_b4: 'Una vez generada tu app, pide cambios en lenguaje natural: «añade modo oscuro», «pon el botón en verde». 🎙️ Hay dos micrófonos: uno envía un mensaje de voz al instante (punto rojo), el otro transcribe tu voz al campo de texto para revisarla antes de enviar.',
    d_t5: '4️⃣ Vista previa instantánea',
    d_b5: 'Mira tu app corriendo inmediatamente, como si ya estuviera desplegada. Web, móvil (PWA) o escritorio — tú eliges.',
    d_t6: '5️⃣ Modo Sin Conexión',
    d_b6: '¿Sin conexión? Con Ollama instalado, genera apps sin enviar datos a internet. 100% privado, 100% gratis.',
    d_t7: '¿Listo para probarlo?',
    d_b7: 'Crea tu cuenta en 30 segundos — solo email y contraseña. Sin tarjeta, sin anuncios, sin cuotas.',
    mic_voice_send: 'Mensaje de voz — habla y envía', mic_voice_text: 'Voz a texto — habla y revisa',
    mic_unsupported: '🎤 Micrófono no compatible con este navegador.',
    mic_permission: '🎤 Permite el acceso al micrófono para usar esta función.',
    mic_too_short: '🎤 Grabación demasiado corta — inténtalo de nuevo.',
    mic_no_text: '🎤 No se detectó voz — habla más claro.',
    mic_failed: '🎤 Falló la transcripción. Inténtalo de nuevo.',
    mic_voice_badge: 'Voz',
  },

  // ========== DEUTSCH ==========
  de: {
    back: 'Zurück', next: 'Weiter', previous: 'Vorherige', generate: 'Generieren',
    loading: 'Lädt…', error: 'Fehler', success: 'Erfolg', cancel: 'Abbrechen',
    save: 'Speichern', delete: 'Löschen', edit: 'Bearbeiten', close: 'Schließen', yes: 'Ja', no: 'Nein',
    loginSignin: 'Anmelden', loginSignup: 'Registrieren',
    loginConnectToContinue: 'Melde dich an, um fortzufahren',
    loginCreateAccount: 'Erstelle dein kostenloses Konto',
    loginEmail: 'E-Mail-Adresse (Gmail bevorzugt)',
    loginPassword: 'Passwort', loginName: 'Name (optional)',
    loginSubmitSignin: 'Anmelden', loginSubmitSignup: 'Konto erstellen',
    loginMagicLink: 'Magic-Link-Anmeldung (ohne Passwort)',
    loginForgot: 'Passwort vergessen?',
    loginSmsDemo: 'SMS-Anmeldung (Demo)',
    loginOrOffline: 'oder Offline-Modus',
    loginBackHome: '← Zurück zur Startseite',
    loginHowItWorks: 'Wie es funktioniert', loginLegal: 'AGB & Datenschutz',
    loginWaitingForConfirm: 'Warte auf Bestätigung…',
    loginEmailMinChars: 'Mindestens 6 Zeichen', loginExpiresIn: 'Läuft ab in',
    loginResendBtn: 'Link erneut senden', loginResendSent: 'Senden…',
    loginResendCooldown: '10 Min warten',
    loginIdleNotice: 'Du wurdest nach 1+ Stunde Inaktivität abgemeldet. Schließe diese Nachricht und melde dich erneut an.',
    dashProjects: 'Projekte', dashNewProject: 'Neues Projekt', dashSwitchAccount: 'Konto wechseln', dashLogout: 'Abmelden',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'KI verfügbar',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Grenzenlose Kreation',
    dashWhatToDo: 'Was möchtest du tun?', dashChooseMode: 'Wähle deinen Arbeitsmodus',
    dashEmptyHint: '✨ Noch keine Projekte — wähle unten einen Modus, um loszulegen (kostenlos & unbegrenzt).',
    dashWizard: 'Geführter Assistent', dashWizardDesc: 'Erstelle dein Projekt Schritt für Schritt mit einfachen Fragen',
    dashChat: 'Chat', dashChatBadgeOn: 'ONLINE-KI', dashChatDescOn: 'Chatte mit einer leistungsstarken KI',
    dashChatBadgeOff: 'OFFLINE-KI', dashChatDescOff: 'Lokale KI (Ollama) ohne Internet',
    dashCreate: 'Erstellen', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Mobile-, Web- und Desktop-Apps erzeugen',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Apps mit lokaler KI (Ollama) erzeugen',
    dashInfoOnline: '💡 Online-Modus: leistungsstarke KI mit Remote-Ollama',
    dashInfoOffline: '🔌 Offline-Modus: erfordert lokal installiertes Ollama',
    dashCollapseSidebar: 'Leiste einklappen', dashExpandSidebar: 'Projekte anzeigen', dashTutorial: 'Tutorial',
    l_navDiscover: 'Entdecken', l_h1Line1: 'Erstelle Anwendungen', l_h1Highlight: 'Anwendungen', l_h1Line2: 'Ohne Code zu schreiben',
    l_subtitle: 'Beschreibe dein Projekt, unsere KI erzeugt sofort den kompletten Code. Web-, Mobile- und Desktop-Apps. Grenzenlos. 100% kostenlos.',
    l_signupBtn: 'Registrieren', l_loginBtn: 'Anmelden',
    l_statUnlimited: 'Unbegrenzte Erzeugung', l_statAI: 'Modernste KI', l_statFormats: 'Web, Mobile, Desktop',
    l_featTitle: 'Eine revolutionäre Plattform', l_featTitleHighlight: 'revolutionäre',
    l_feat1T: 'Intelligente Erzeugung', l_feat1D: 'Unsere KI analysiert deine Beschreibung und erzeugt sofort professionellen Code.',
    l_feat2T: 'Mobile Apps (.apk)', l_feat2D: 'Exportiere direkt nach Android. Installation per Klick auf deinem Telefon.',
    l_feat3T: 'Desktop-Software (.exe)', l_feat3D: 'Erstelle professionelle Windows-Anwendungen, bereit zur Verteilung.',
    l_feat4T: 'Webseiten', l_feat4D: 'Sofort im Web bereitstellen mit integriertem Hosting.',
    l_feat5T: 'Offline-Modus', l_feat5D: 'Weiter erstellen, auch ohne Internet. Automatischer Wechsel.',
    l_feat6T: 'Ohne Einschränkungen', l_feat6D: 'Keine Nutzungsgrenzen. Keine Credits. Volle Kreativität.',
    l_ctaTitle: 'Bereit, grenzenlos zu erstellen?', l_ctaSub: 'Werde Teil der KI-gestützten Entwicklungsrevolution.',
    l_ctaBtn: 'Jetzt starten',
    l_footer: '© 2026 CodeForge AI. Angetrieben von Emergent AI. Ohne Einschränkungen, ohne Grenzen.',
    d_exit: 'Tour verlassen', d_step: 'Schritt', d_login: 'Anmelden',
    d_prev: 'Zurück', d_next: 'Weiter', d_signup: 'Registrieren',
    d_kbTip: 'Tipp: benutze die Pfeiltasten ← →, um zu navigieren.',
    d_locked: '🔒 Melde dich an, um diese Funktion zu nutzen.', d_preview: 'Vorschau',
    d_t1: 'Willkommen bei CodeForge AI',
    d_b1: 'Das ist dein zukünftiges Dashboard. Mit den Pfeilen erkundest du jeden Bildschirm. Nach Registrierung kannst du alles nutzen.',
    d_t2: '1️⃣ Geführter Assistent',
    d_b2: 'Die KI stellt 4-5 einfache Fragen (App-Typ, Name, Farben, Plattform) und erzeugt das vollständige Projekt.',
    d_t3: '2️⃣ Freies Erstellen',
    d_b3: 'Beschreibe deine App in einem Satz: „Eine Rezeptseite mit 5-Sterne-Bewertung". Die KI erzeugt den vollen Code in unter einer Minute.',
    d_t4: '3️⃣ Chat mit der KI',
    d_b4: 'Nach der Erzeugung kannst du Änderungen in natürlicher Sprache anfragen: „Dark Mode hinzufügen", „Knopf grün". 🎙️ Zwei Mikrofone stehen bereit: eines sendet sofort eine Sprachnachricht (roter Punkt), das andere transkribiert deine Stimme ins Textfeld zur Überprüfung vor dem Senden.',
    d_t5: '4️⃣ Sofort-Vorschau',
    d_b5: 'Sieh deine App sofort laufen, als wäre sie schon bereitgestellt. Web, Mobile (PWA) oder Desktop — deine Wahl.',
    d_t6: '5️⃣ Offline-Modus',
    d_b6: 'Kein Internet? Mit Ollama auf deinem PC erzeugst du Apps, ohne Daten zu senden. 100% privat, 100% kostenlos.',
    d_t7: 'Bereit zum Ausprobieren?',
    d_b7: 'Erstelle dein Konto in 30 Sekunden — nur E-Mail und Passwort. Keine Karte, keine Werbung, keine Quoten.',
    mic_voice_send: 'Sprachnachricht — sprechen & senden', mic_voice_text: 'Sprache zu Text — sprechen & prüfen',
    mic_unsupported: '🎤 Mikrofon in diesem Browser nicht unterstützt.',
    mic_permission: '🎤 Bitte erlaube den Zugriff auf das Mikrofon.',
    mic_too_short: '🎤 Aufnahme zu kurz — bitte erneut versuchen.',
    mic_no_text: '🎤 Keine Sprache erkannt — sprich deutlicher.',
    mic_failed: '🎤 Transkription fehlgeschlagen. Bitte erneut versuchen.',
    mic_voice_badge: 'Sprache',
  },

  // ========== NEDERLANDS ==========
  nl: {
    back: 'Terug', next: 'Volgende', previous: 'Vorige', generate: 'Genereren',
    loading: 'Laden…', error: 'Fout', success: 'Gelukt', cancel: 'Annuleren',
    save: 'Opslaan', delete: 'Verwijderen', edit: 'Bewerken', close: 'Sluiten', yes: 'Ja', no: 'Nee',
    loginSignin: 'Inloggen', loginSignup: 'Aanmelden',
    loginConnectToContinue: 'Log in om door te gaan',
    loginCreateAccount: 'Maak je gratis account aan',
    loginEmail: 'E-mailadres (Gmail aanbevolen)',
    loginPassword: 'Wachtwoord', loginName: 'Naam (optioneel)',
    loginSubmitSignin: 'Inloggen', loginSubmitSignup: 'Account aanmaken',
    loginMagicLink: 'Inloggen via magic link (zonder wachtwoord)',
    loginForgot: 'Wachtwoord vergeten?',
    loginSmsDemo: 'SMS-login (demo)',
    loginOrOffline: 'of offline modus',
    loginBackHome: '← Terug naar home',
    loginHowItWorks: 'Hoe het werkt', loginLegal: 'Voorwaarden & Privacy',
    loginWaitingForConfirm: 'Wachten op bevestiging…',
    loginEmailMinChars: 'Minimaal 6 tekens', loginExpiresIn: 'Verloopt over',
    loginResendBtn: 'Link opnieuw versturen', loginResendSent: 'Bezig…',
    loginResendCooldown: 'Wacht 10 min',
    loginIdleNotice: 'Je bent uitgelogd na 1 uur of meer inactiviteit. Sluit dit bericht en log opnieuw in.',
    dashProjects: 'Projecten', dashNewProject: 'Nieuw project', dashSwitchAccount: 'Account wisselen', dashLogout: 'Uitloggen',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'AI beschikbaar',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Onbeperkt creëren',
    dashWhatToDo: 'Wat wil je doen?', dashChooseMode: 'Kies je werkmodus',
    dashEmptyHint: '✨ Nog geen projecten — kies hieronder een modus om te beginnen (gratis & onbeperkt).',
    dashWizard: 'Begeleide wizard', dashWizardDesc: 'Maak je project stap voor stap met simpele vragen',
    dashChat: 'Chat', dashChatBadgeOn: 'ONLINE AI', dashChatDescOn: 'Chat met een krachtige AI',
    dashChatBadgeOff: 'OFFLINE AI', dashChatDescOff: 'Lokale AI (Ollama) zonder internet',
    dashCreate: 'Maken', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Genereer mobiele, web- en desktop-apps',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Genereer apps met lokale AI (Ollama)',
    dashInfoOnline: '💡 Online modus: krachtige AI met externe Ollama',
    dashInfoOffline: '🔌 Offline modus: vereist Ollama lokaal geïnstalleerd',
    dashCollapseSidebar: 'Balk inklappen', dashExpandSidebar: 'Projecten tonen', dashTutorial: 'Rondleiding',
    l_navDiscover: 'Ontdekken', l_h1Line1: 'Maak Applicaties', l_h1Highlight: 'Applicaties', l_h1Line2: 'Zonder Code te Schrijven',
    l_subtitle: 'Beschrijf je project, onze AI genereert direct de volledige code. Web-, mobiele en desktop-apps. Geen limieten. 100% gratis.',
    l_signupBtn: 'Aanmelden', l_loginBtn: 'Inloggen',
    l_statUnlimited: 'Onbeperkte Generatie', l_statAI: 'Geavanceerde AI', l_statFormats: 'Web, Mobiel, Desktop',
    l_featTitle: 'Een Revolutionair Platform', l_featTitleHighlight: 'Revolutionair',
    l_feat1T: 'Slimme Generatie', l_feat1D: 'Onze AI analyseert je beschrijving en genereert direct professionele code.',
    l_feat2T: 'Mobiele Apps (.apk)', l_feat2D: 'Exporteer direct naar Android. Eén klik installatie op je telefoon.',
    l_feat3T: 'Desktop Software (.exe)', l_feat3D: 'Maak professionele Windows-applicaties klaar voor distributie.',
    l_feat4T: 'Websites', l_feat4D: 'Direct op het web publiceren met geïntegreerde hosting.',
    l_feat5T: 'Offline Modus', l_feat5D: 'Blijf creëren, ook zonder internet. Automatische omschakeling.',
    l_feat6T: 'Zonder Beperkingen', l_feat6D: 'Geen gebruikslimieten. Geen credits. Totale creativiteit.',
    l_ctaTitle: 'Klaar om Onbeperkt te Bouwen?', l_ctaSub: 'Doe mee met de AI-ondersteunde ontwikkelingsrevolutie.',
    l_ctaBtn: 'Nu Beginnen',
    l_footer: '© 2026 CodeForge AI. Aangedreven door Emergent AI. Zonder beperkingen, zonder limieten.',
    d_exit: 'Rondleiding verlaten', d_step: 'Stap', d_login: 'Inloggen',
    d_prev: 'Vorige', d_next: 'Volgende', d_signup: 'Aanmelden',
    d_kbTip: 'Tip: gebruik de ← → pijltjestoetsen om te navigeren.',
    d_locked: '🔒 Log in om deze functie te gebruiken.', d_preview: 'voorbeeld',
    d_t1: 'Welkom bij CodeForge AI',
    d_b1: 'Dit is je toekomstige dashboard. Gebruik de pijlen om elk scherm te ontdekken. Na aanmelding kun je alles gebruiken.',
    d_t2: '1️⃣ Begeleide Wizard',
    d_b2: 'De AI stelt 4-5 simpele vragen (app-type, naam, kleuren, platform) en genereert het volledige project.',
    d_t3: '2️⃣ Vrij creëren',
    d_b3: 'Beschrijf je app in één zin: "een receptensite met 5-sterren beoordeling". De AI genereert de volledige code in minder dan een minuut.',
    d_t4: '3️⃣ Chat met de AI',
    d_b4: 'Vraag wijzigingen in natuurlijke taal: "voeg dark mode toe", "maak de knop groen". 🎙️ Twee microfoons beschikbaar: één stuurt direct een spraakbericht (rode stip), de ander zet je spraak om in het tekstveld zodat je kunt nakijken vóór verzending.',
    d_t5: '4️⃣ Direct voorbeeld',
    d_b5: 'Zie je app meteen draaien, alsof hij al online staat. Web, mobiel (PWA) of desktop — jouw keuze.',
    d_t6: '5️⃣ Offline Modus',
    d_b6: 'Geen internet? Met Ollama op je PC genereer je apps zonder data te versturen. 100% privé, 100% gratis.',
    d_t7: 'Klaar om te proberen?',
    d_b7: 'Maak je account in 30 seconden — alleen e-mail en wachtwoord. Geen kaart, geen reclame, geen quota.',
    mic_voice_send: 'Spraakbericht — spreek & verzend', mic_voice_text: 'Spraak naar tekst — spreek & controleer',
    mic_unsupported: '🎤 Microfoon niet ondersteund in deze browser.',
    mic_permission: '🎤 Geef toestemming voor de microfoon.',
    mic_too_short: '🎤 Opname te kort — probeer opnieuw.',
    mic_no_text: '🎤 Geen spraak gedetecteerd — spreek duidelijker.',
    mic_failed: '🎤 Transcriptie mislukt. Probeer opnieuw.',
    mic_voice_badge: 'Spraak',
  },

  // ========== РУССКИЙ ==========
  ru: {
    back: 'Назад', next: 'Далее', previous: 'Предыдущее', generate: 'Создать',
    loading: 'Загрузка…', error: 'Ошибка', success: 'Успех', cancel: 'Отмена',
    save: 'Сохранить', delete: 'Удалить', edit: 'Изменить', close: 'Закрыть', yes: 'Да', no: 'Нет',
    loginSignin: 'Войти', loginSignup: 'Регистрация',
    loginConnectToContinue: 'Войдите, чтобы продолжить',
    loginCreateAccount: 'Создайте бесплатный аккаунт',
    loginEmail: 'Адрес эл. почты (предпочтительно Gmail)',
    loginPassword: 'Пароль', loginName: 'Имя (необязательно)',
    loginSubmitSignin: 'Войти', loginSubmitSignup: 'Создать аккаунт',
    loginMagicLink: 'Вход по волшебной ссылке (без пароля)',
    loginForgot: 'Забыли пароль?',
    loginSmsDemo: 'Вход по SMS (демо)',
    loginOrOffline: 'или офлайн-режим',
    loginBackHome: '← На главную',
    loginHowItWorks: 'Как это работает', loginLegal: 'Условия и Конфиденциальность',
    loginWaitingForConfirm: 'Ожидание подтверждения…',
    loginEmailMinChars: 'Минимум 6 символов', loginExpiresIn: 'Истекает через',
    loginResendBtn: 'Отправить ссылку снова', loginResendSent: 'Отправка…',
    loginResendCooldown: 'Подождите 10 мин',
    loginIdleNotice: 'Вы вышли после 1+ часа бездействия. Закройте это сообщение и войдите снова.',
    dashProjects: 'Проекты', dashNewProject: 'Новый проект', dashSwitchAccount: 'Сменить аккаунт', dashLogout: 'Выйти',
    dashOnline: 'Онлайн', dashOffline: 'Офлайн', dashAiAvailable: 'ИИ доступен',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Создание без ограничений',
    dashWhatToDo: 'Что вы хотите сделать?', dashChooseMode: 'Выберите режим работы',
    dashEmptyHint: '✨ Пока нет проектов — выберите режим ниже, чтобы начать (бесплатно и без ограничений).',
    dashWizard: 'Помощник', dashWizardDesc: 'Создайте проект шаг за шагом с простыми вопросами',
    dashChat: 'Чат', dashChatBadgeOn: 'ОНЛАЙН-ИИ', dashChatDescOn: 'Общайтесь с мощным ИИ',
    dashChatBadgeOff: 'ОФЛАЙН-ИИ', dashChatDescOff: 'Локальный ИИ (Ollama) без интернета',
    dashCreate: 'Создать', dashCreateBadgeOn: 'ОНЛАЙН', dashCreateDescOn: 'Создавайте мобильные, веб- и десктоп-приложения',
    dashCreateBadgeOff: 'ОФЛАЙН', dashCreateDescOff: 'Создавайте приложения с локальным ИИ (Ollama)',
    dashInfoOnline: '💡 Онлайн-режим: мощный ИИ с удалённым Ollama',
    dashInfoOffline: '🔌 Офлайн-режим: требуется установленный локально Ollama',
    dashCollapseSidebar: 'Свернуть панель', dashExpandSidebar: 'Показать проекты', dashTutorial: 'Обучение',
    l_navDiscover: 'Узнать больше', l_h1Line1: 'Создавайте Приложения', l_h1Highlight: 'Приложения', l_h1Line2: 'Без Написания Кода',
    l_subtitle: 'Опишите проект — наш ИИ мгновенно создаст полный код. Веб, мобильные и десктопные приложения. Без ограничений. 100% бесплатно.',
    l_signupBtn: 'Регистрация', l_loginBtn: 'Войти',
    l_statUnlimited: 'Безлимитная генерация', l_statAI: 'Передовой ИИ', l_statFormats: 'Веб, Мобильное, Десктоп',
    l_featTitle: 'Революционная платформа', l_featTitleHighlight: 'Революционная',
    l_feat1T: 'Умная генерация', l_feat1D: 'ИИ анализирует ваше описание и мгновенно создаёт профессиональный код.',
    l_feat2T: 'Мобильные приложения (.apk)', l_feat2D: 'Экспорт прямо на Android. Установка в один клик.',
    l_feat3T: 'Десктоп ПО (.exe)', l_feat3D: 'Создавайте профессиональные приложения Windows, готовые к распространению.',
    l_feat4T: 'Веб-сайты', l_feat4D: 'Мгновенный деплой со встроенным хостингом.',
    l_feat5T: 'Оффлайн-режим', l_feat5D: 'Продолжайте создавать даже без интернета. Автопереключение.',
    l_feat6T: 'Без ограничений', l_feat6D: 'Никаких лимитов. Никаких кредитов. Полная свобода.',
    l_ctaTitle: 'Готовы создавать без ограничений?', l_ctaSub: 'Присоединяйтесь к революции разработки с ИИ.',
    l_ctaBtn: 'Начать сейчас',
    l_footer: '© 2026 CodeForge AI. На базе Emergent AI. Без ограничений и лимитов.',
    d_exit: 'Выйти из тура', d_step: 'Шаг', d_login: 'Войти',
    d_prev: 'Назад', d_next: 'Далее', d_signup: 'Регистрация',
    d_kbTip: 'Совет: используйте стрелки ← → на клавиатуре для навигации.',
    d_locked: '🔒 Войдите, чтобы использовать эту функцию.', d_preview: 'предпросмотр',
    d_t1: 'Добро пожаловать в CodeForge AI',
    d_b1: 'Вот ваш будущий дашборд. Используйте стрелки, чтобы изучить каждый экран. После регистрации всё станет доступно.',
    d_t2: '1️⃣ Помощник', d_b2: 'ИИ задаёт 4-5 простых вопросов (тип приложения, имя, цвета, платформа) и создаёт полный проект.',
    d_t3: '2️⃣ Свободное создание', d_b3: 'Опишите приложение одной фразой: «сайт рецептов с 5-звёздочной оценкой». ИИ создаст код менее чем за минуту.',
    d_t4: '3️⃣ Чат с ИИ', d_b4: 'Просите изменения на естественном языке: «добавь тёмную тему», «сделай кнопку зелёной». 🎙️ Доступны два микрофона: один отправляет голосовое сообщение мгновенно (красная точка), другой переводит вашу речь в текстовое поле для проверки перед отправкой.',
    d_t5: '4️⃣ Мгновенный предпросмотр', d_b5: 'Посмотрите, как приложение работает, словно оно уже развёрнуто. Веб, мобильное (PWA) или десктоп — на выбор.',
    d_t6: '5️⃣ Оффлайн-режим', d_b6: 'Нет интернета? С Ollama на вашем ПК создавайте приложения без передачи данных. 100% приватно, 100% бесплатно.',
    d_t7: 'Готовы попробовать?', d_b7: 'Создайте аккаунт за 30 секунд — только email и пароль. Без карты, без рекламы, без квот.',
    mic_voice_send: 'Голосовое сообщение — говори и отправь', mic_voice_text: 'Голос в текст — говори и проверь',
    mic_unsupported: '🎤 Микрофон не поддерживается в этом браузере.',
    mic_permission: '🎤 Разрешите доступ к микрофону.',
    mic_too_short: '🎤 Запись слишком короткая — попробуйте ещё раз.',
    mic_no_text: '🎤 Речь не распознана — говорите чётче.',
    mic_failed: '🎤 Не удалось расшифровать. Попробуйте ещё раз.',
    mic_voice_badge: 'Голос',
  },

  // ========== 中文 简体 (Chinese Simplified) ==========
  zh: {
    back: '返回', next: '下一步', previous: '上一步', generate: '生成',
    loading: '加载中…', error: '错误', success: '成功', cancel: '取消',
    save: '保存', delete: '删除', edit: '编辑', close: '关闭', yes: '是', no: '否',
    loginSignin: '登录', loginSignup: '注册',
    loginConnectToContinue: '登录以继续',
    loginCreateAccount: '免费创建账户',
    loginEmail: '电子邮件 (推荐使用 Gmail)',
    loginPassword: '密码', loginName: '姓名 (可选)',
    loginSubmitSignin: '登录', loginSubmitSignup: '创建账户',
    loginMagicLink: '魔法链接登录 (无需密码)',
    loginForgot: '忘记密码？',
    loginSmsDemo: '短信登录 (演示)',
    loginOrOffline: '或离线模式',
    loginBackHome: '← 返回首页',
    loginHowItWorks: '使用说明', loginLegal: '服务条款与隐私',
    loginWaitingForConfirm: '等待确认…',
    loginEmailMinChars: '至少 6 个字符', loginExpiresIn: '到期时间',
    loginResendBtn: '重新发送链接', loginResendSent: '发送中…',
    loginResendCooldown: '请等待 10 分钟',
    loginIdleNotice: '由于超过 1 小时未活动，您已被自动注销。请关闭此消息后重新登录。',
    dashProjects: '项目', dashNewProject: '新建项目', dashSwitchAccount: '切换账户', dashLogout: '退出登录',
    dashOnline: '在线', dashOffline: '离线', dashAiAvailable: 'AI 可用',
    dashTitle: 'CodeForge AI', dashSubtitle: '无限创作',
    dashWhatToDo: '你想做什么？', dashChooseMode: '选择你的工作模式',
    dashEmptyHint: '✨ 还没有项目 — 选择下方模式开始吧（免费、无限制）。',
    dashWizard: '引导式向导', dashWizardDesc: '通过简单的问题逐步创建你的项目',
    dashChat: '聊天', dashChatBadgeOn: '在线 AI', dashChatDescOn: '与强大的 AI 交流',
    dashChatBadgeOff: '离线 AI', dashChatDescOff: '本地 AI (Ollama)，无需联网',
    dashCreate: '创建', dashCreateBadgeOn: '在线', dashCreateDescOn: '生成移动端、网页、桌面应用',
    dashCreateBadgeOff: '离线', dashCreateDescOff: '使用本地 AI (Ollama) 生成应用',
    dashInfoOnline: '💡 在线模式：使用远程 Ollama 的强大 AI',
    dashInfoOffline: '🔌 离线模式：需要本地安装 Ollama',
    dashCollapseSidebar: '收起侧栏', dashExpandSidebar: '显示项目', dashTutorial: '教程',
    l_navDiscover: '探索', l_h1Line1: '构建应用', l_h1Highlight: '应用', l_h1Line2: '无需编写代码',
    l_subtitle: '描述你的项目，AI 即时生成完整代码。Web、移动端、桌面应用。无限制。100% 免费。',
    l_signupBtn: '注册', l_loginBtn: '登录',
    l_statUnlimited: '无限生成', l_statAI: '尖端 AI', l_statFormats: 'Web, 移动端, 桌面',
    l_featTitle: '革命性的平台', l_featTitleHighlight: '革命性的',
    l_feat1T: '智能生成', l_feat1D: 'AI 分析你的描述，瞬间生成专业代码。',
    l_feat2T: '移动应用 (.apk)', l_feat2D: '直接导出到 Android，一键安装到手机。',
    l_feat3T: '桌面软件 (.exe)', l_feat3D: '创建可分发的专业 Windows 应用。',
    l_feat4T: '网站', l_feat4D: '集成托管，瞬间部署到 Web。',
    l_feat5T: '离线模式', l_feat5D: '没有网络也能继续创作，自动切换。',
    l_feat6T: '无限制', l_feat6D: '没有使用限制，没有积分，完全自由。',
    l_ctaTitle: '准备好无限创作了吗？', l_ctaSub: '加入 AI 辅助开发的革命。',
    l_ctaBtn: '立即开始',
    l_footer: '© 2026 CodeForge AI。由 Emergent AI 提供支持。无限制、无配额。',
    d_exit: '退出导览', d_step: '步骤', d_login: '登录',
    d_prev: '上一步', d_next: '下一步', d_signup: '注册',
    d_kbTip: '提示：使用键盘的 ← → 方向键导航。',
    d_locked: '🔒 登录后即可使用此功能。', d_preview: '预览',
    d_t1: '欢迎来到 CodeForge AI',
    d_b1: '这是你未来的仪表盘。用箭头浏览每个界面。注册后即可使用全部功能。',
    d_t2: '1️⃣ 引导式向导', d_b2: 'AI 会问 4-5 个简单问题（应用类型、名称、颜色、平台），然后生成完整项目。',
    d_t3: '2️⃣ 自由创作', d_b3: '用一句话描述你的应用，比如"带 5 星评分的菜谱网站"。AI 一分钟内生成完整代码。',
    d_t4: '3️⃣ 与 AI 对话', d_b4: '用自然语言提出修改："加暗黑模式"、"按钮改成绿色"。🎙️ 提供两个麦克风：一个直接发送语音消息（红点），另一个把你的语音转写到文本框，便于发送前检查。',
    d_t5: '4️⃣ 即时预览', d_b5: '立即看到应用运行，就像已经部署一样。Web、移动 (PWA) 或桌面 — 任你选择。',
    d_t6: '5️⃣ 离线模式', d_b6: '没有网络？在你的电脑上安装 Ollama，本地生成应用，不上传任何数据。100% 私密，100% 免费。',
    d_t7: '准备好试试了吗？', d_b7: '30 秒创建账户 — 只需邮箱和密码。无需信用卡、无广告、无配额。',
    mic_voice_send: '语音消息 — 说话即发送', mic_voice_text: '语音转文字 — 说话后查看',
    mic_unsupported: '🎤 此浏览器不支持麦克风。',
    mic_permission: '🎤 请允许使用麦克风。',
    mic_too_short: '🎤 录音太短 — 请重试。',
    mic_no_text: '🎤 未检测到语音 — 请清晰发音。',
    mic_failed: '🎤 转录失败，请重试。',
    mic_voice_badge: '语音',
  },

  // ========== 中文 繁體 (Chinese Traditional) ==========
  'zh-TW': {
    back: '返回', next: '下一步', previous: '上一步', generate: '生成',
    loading: '載入中…', error: '錯誤', success: '成功', cancel: '取消',
    save: '儲存', delete: '刪除', edit: '編輯', close: '關閉', yes: '是', no: '否',
    loginSignin: '登入', loginSignup: '註冊',
    loginConnectToContinue: '登入以繼續',
    loginCreateAccount: '免費建立帳戶',
    loginEmail: '電子郵件 (建議使用 Gmail)',
    loginPassword: '密碼', loginName: '姓名 (可選)',
    loginSubmitSignin: '登入', loginSubmitSignup: '建立帳戶',
    loginMagicLink: '魔法連結登入 (免密碼)',
    loginForgot: '忘記密碼？',
    loginSmsDemo: '簡訊登入 (示範)',
    loginOrOffline: '或離線模式',
    loginBackHome: '← 返回首頁',
    loginHowItWorks: '使用說明', loginLegal: '服務條款與隱私',
    loginWaitingForConfirm: '等待確認…',
    loginEmailMinChars: '至少 6 個字元', loginExpiresIn: '到期時間',
    loginResendBtn: '重新傳送連結', loginResendSent: '傳送中…',
    loginResendCooldown: '請等待 10 分鐘',
    loginIdleNotice: '由於超過 1 小時未操作，您已被自動登出。請關閉此訊息後重新登入。',
    dashProjects: '專案', dashNewProject: '新增專案', dashSwitchAccount: '切換帳戶', dashLogout: '登出',
    dashOnline: '線上', dashOffline: '離線', dashAiAvailable: 'AI 可用',
    dashTitle: 'CodeForge AI', dashSubtitle: '無限創作',
    dashWhatToDo: '你想做什麼？', dashChooseMode: '選擇你的工作模式',
    dashEmptyHint: '✨ 還沒有專案 — 選擇下方模式開始吧（免費、無限制）。',
    dashWizard: '引導式精靈', dashWizardDesc: '透過簡單的問題逐步建立你的專案',
    dashChat: '聊天', dashChatBadgeOn: '線上 AI', dashChatDescOn: '與強大的 AI 對話',
    dashChatBadgeOff: '離線 AI', dashChatDescOff: '本機 AI (Ollama)，無須連網',
    dashCreate: '建立', dashCreateBadgeOn: '線上', dashCreateDescOn: '產生行動、網頁、桌面應用',
    dashCreateBadgeOff: '離線', dashCreateDescOff: '使用本機 AI (Ollama) 產生應用',
    dashInfoOnline: '💡 線上模式：使用遠端 Ollama 的強大 AI',
    dashInfoOffline: '🔌 離線模式：需要本機安裝 Ollama',
    dashCollapseSidebar: '收合側邊欄', dashExpandSidebar: '顯示專案', dashTutorial: '教學',
    l_navDiscover: '探索', l_h1Line1: '建立應用', l_h1Highlight: '應用', l_h1Line2: '無需編寫程式碼',
    l_subtitle: '描述你的專案，AI 即時產生完整程式碼。Web、行動、桌面應用。無限制。100% 免費。',
    l_signupBtn: '註冊', l_loginBtn: '登入',
    l_statUnlimited: '無限產生', l_statAI: '尖端 AI', l_statFormats: 'Web, 行動, 桌面',
    l_featTitle: '革命性的平台', l_featTitleHighlight: '革命性的',
    l_feat1T: '智慧產生', l_feat1D: 'AI 分析你的描述，瞬間產生專業程式碼。',
    l_feat2T: '行動應用 (.apk)', l_feat2D: '直接匯出到 Android，一鍵安裝到手機。',
    l_feat3T: '桌面軟體 (.exe)', l_feat3D: '建立可發佈的專業 Windows 應用。',
    l_feat4T: '網站', l_feat4D: '整合主機，瞬間部署到 Web。',
    l_feat5T: '離線模式', l_feat5D: '沒有網路也能繼續創作，自動切換。',
    l_feat6T: '無限制', l_feat6D: '沒有使用限制，沒有點數，完全自由。',
    l_ctaTitle: '準備好無限創作了嗎？', l_ctaSub: '加入 AI 輔助開發的革命。',
    l_ctaBtn: '立即開始',
    l_footer: '© 2026 CodeForge AI。由 Emergent AI 提供支援。無限制、無配額。',
    d_exit: '退出導覽', d_step: '步驟', d_login: '登入',
    d_prev: '上一步', d_next: '下一步', d_signup: '註冊',
    d_kbTip: '提示：使用鍵盤的 ← → 方向鍵導覽。',
    d_locked: '🔒 登入後即可使用此功能。', d_preview: '預覽',
    d_t1: '歡迎使用 CodeForge AI',
    d_b1: '這是你未來的儀表板。用箭頭瀏覽每個畫面。註冊後即可使用全部功能。',
    d_t2: '1️⃣ 引導式精靈', d_b2: 'AI 會問 4-5 個簡單問題（應用類型、名稱、色彩、平台），然後產生完整專案。',
    d_t3: '2️⃣ 自由建立', d_b3: '用一句話描述你的應用，例如「帶 5 星評分的食譜網站」。AI 一分鐘內產生完整程式碼。',
    d_t4: '3️⃣ 與 AI 對話', d_b4: '用自然語言提出修改：「加深色模式」、「按鈕改成綠色」。🎙️ 提供兩個麥克風：一個直接傳送語音訊息（紅點），另一個把你的語音轉寫到文字框，便於傳送前檢查。',
    d_t5: '4️⃣ 即時預覽', d_b5: '立即看到應用運行，就像已經部署一樣。Web、行動 (PWA) 或桌面 — 任你選擇。',
    d_t6: '5️⃣ 離線模式', d_b6: '沒有網路？在你的電腦上安裝 Ollama，本機產生應用，不上傳任何資料。100% 私密、100% 免費。',
    d_t7: '準備好試試了嗎？', d_b7: '30 秒建立帳戶 — 只需電子郵件和密碼。無需信用卡、無廣告、無配額。',
    mic_voice_send: '語音訊息 — 說話即傳送', mic_voice_text: '語音轉文字 — 說話後檢查',
    mic_unsupported: '🎤 此瀏覽器不支援麥克風。',
    mic_permission: '🎤 請允許使用麥克風。',
    mic_too_short: '🎤 錄音太短 — 請重試。',
    mic_no_text: '🎤 未偵測到語音 — 請清晰發音。',
    mic_failed: '🎤 轉錄失敗，請重試。',
    mic_voice_badge: '語音',
  },

  // ========== हिन्दी (Hindi) ==========
  hi: {
    back: 'वापस', next: 'अगला', previous: 'पिछला', generate: 'बनाएँ',
    loading: 'लोड हो रहा है…', error: 'त्रुटि', success: 'सफलता', cancel: 'रद्द करें',
    save: 'सहेजें', delete: 'हटाएँ', edit: 'संपादित करें', close: 'बंद करें', yes: 'हाँ', no: 'नहीं',
    loginSignin: 'साइन इन', loginSignup: 'साइन अप',
    loginConnectToContinue: 'जारी रखने के लिए साइन इन करें',
    loginCreateAccount: 'अपना मुफ़्त खाता बनाएँ',
    loginEmail: 'ईमेल पता (Gmail अनुशंसित)',
    loginPassword: 'पासवर्ड', loginName: 'नाम (वैकल्पिक)',
    loginSubmitSignin: 'साइन इन', loginSubmitSignup: 'खाता बनाएँ',
    loginMagicLink: 'मैजिक लिंक साइन-इन (बिना पासवर्ड)',
    loginForgot: 'पासवर्ड भूल गए?',
    loginSmsDemo: 'SMS साइन-इन (डेमो)',
    loginOrOffline: 'या ऑफ़लाइन मोड',
    loginBackHome: '← होम पर वापस',
    loginHowItWorks: 'यह कैसे काम करता है', loginLegal: 'नियम और गोपनीयता',
    loginWaitingForConfirm: 'पुष्टि की प्रतीक्षा है…',
    loginEmailMinChars: 'न्यूनतम 6 अक्षर', loginExpiresIn: 'समाप्त होगा',
    loginResendBtn: 'लिंक फिर भेजें', loginResendSent: 'भेज रहे हैं…',
    loginResendCooldown: '10 मिनट प्रतीक्षा करें',
    loginIdleNotice: '1 घंटे या अधिक की निष्क्रियता के बाद आपको लॉग आउट कर दिया गया है। यह संदेश बंद करें और फिर से साइन इन करें।',
    dashProjects: 'प्रोजेक्ट', dashNewProject: 'नया प्रोजेक्ट', dashSwitchAccount: 'खाता बदलें', dashLogout: 'लॉग आउट',
    dashOnline: 'ऑनलाइन', dashOffline: 'ऑफ़लाइन', dashAiAvailable: 'AI उपलब्ध',
    dashTitle: 'CodeForge AI', dashSubtitle: 'असीमित निर्माण',
    dashWhatToDo: 'आप क्या करना चाहते हैं?', dashChooseMode: 'अपना कार्य मोड चुनें',
    dashEmptyHint: '✨ अभी कोई प्रोजेक्ट नहीं — शुरू करने के लिए नीचे एक मोड चुनें (मुफ़्त और असीमित)।',
    dashWizard: 'गाइडेड विज़ार्ड', dashWizardDesc: 'सरल प्रश्नों के साथ चरण-दर-चरण अपना प्रोजेक्ट बनाएं',
    dashChat: 'चैट', dashChatBadgeOn: 'ऑनलाइन AI', dashChatDescOn: 'शक्तिशाली AI से बातचीत करें',
    dashChatBadgeOff: 'ऑफ़लाइन AI', dashChatDescOff: 'इंटरनेट के बिना स्थानीय AI (Ollama)',
    dashCreate: 'बनाएं', dashCreateBadgeOn: 'ऑनलाइन', dashCreateDescOn: 'मोबाइल, वेब, डेस्कटॉप ऐप्स बनाएं',
    dashCreateBadgeOff: 'ऑफ़लाइन', dashCreateDescOff: 'स्थानीय AI (Ollama) से ऐप्स बनाएं',
    dashInfoOnline: '💡 ऑनलाइन मोड: रिमोट Ollama के साथ शक्तिशाली AI',
    dashInfoOffline: '🔌 ऑफ़लाइन मोड: स्थानीय रूप से Ollama इंस्टॉल होना आवश्यक',
    dashCollapseSidebar: 'साइडबार छुपाएं', dashExpandSidebar: 'प्रोजेक्ट दिखाएं', dashTutorial: 'ट्यूटोरियल',
    l_navDiscover: 'खोजें', l_h1Line1: 'एप्लिकेशन बनाएं', l_h1Highlight: 'एप्लिकेशन', l_h1Line2: 'कोड लिखे बिना',
    l_subtitle: 'अपने प्रोजेक्ट का वर्णन करें, हमारा AI तुरंत पूरा कोड बना देता है। वेब, मोबाइल और डेस्कटॉप ऐप्स। बिना सीमा। 100% मुफ़्त।',
    l_signupBtn: 'साइन अप', l_loginBtn: 'साइन इन',
    l_statUnlimited: 'असीमित निर्माण', l_statAI: 'अत्याधुनिक AI', l_statFormats: 'वेब, मोबाइल, डेस्कटॉप',
    l_featTitle: 'एक क्रांतिकारी प्लेटफ़ॉर्म', l_featTitleHighlight: 'क्रांतिकारी',
    l_feat1T: 'स्मार्ट जनरेशन', l_feat1D: 'हमारा AI आपके विवरण का विश्लेषण करता है और तुरंत पेशेवर कोड बनाता है।',
    l_feat2T: 'मोबाइल ऐप्स (.apk)', l_feat2D: 'सीधे Android पर एक्सपोर्ट करें। एक क्लिक में फ़ोन पर इंस्टॉल।',
    l_feat3T: 'डेस्कटॉप सॉफ़्टवेयर (.exe)', l_feat3D: 'वितरण के लिए तैयार पेशेवर Windows ऐप्स बनाएं।',
    l_feat4T: 'वेबसाइट्स', l_feat4D: 'एकीकृत होस्टिंग के साथ तुरंत वेब पर डिप्लॉय करें।',
    l_feat5T: 'ऑफ़लाइन मोड', l_feat5D: 'इंटरनेट के बिना भी बनाते रहें। स्वचालित स्विच।',
    l_feat6T: 'बिना प्रतिबंध', l_feat6D: 'कोई उपयोग सीमा नहीं। कोई क्रेडिट नहीं। पूर्ण रचनात्मकता।',
    l_ctaTitle: 'बिना सीमा बनाने के लिए तैयार?', l_ctaSub: 'AI-सहायता विकास क्रांति में शामिल हों।',
    l_ctaBtn: 'अभी शुरू करें',
    l_footer: '© 2026 CodeForge AI। Emergent AI द्वारा संचालित। बिना प्रतिबंध, बिना सीमा।',
    d_exit: 'दौरा छोड़ें', d_step: 'चरण', d_login: 'साइन इन',
    d_prev: 'पिछला', d_next: 'अगला', d_signup: 'साइन अप',
    d_kbTip: 'सुझाव: नेविगेट करने के लिए कीबोर्ड के ← → तीरों का उपयोग करें।',
    d_locked: '🔒 इस सुविधा का उपयोग करने के लिए साइन इन करें।', d_preview: 'पूर्वावलोकन',
    d_t1: 'CodeForge AI में आपका स्वागत है',
    d_b1: 'यह आपका भावी डैशबोर्ड है। प्रत्येक स्क्रीन देखने के लिए तीरों का उपयोग करें। साइन अप के बाद सब कुछ उपलब्ध होगा।',
    d_t2: '1️⃣ गाइडेड विज़ार्ड', d_b2: 'AI 4-5 सरल प्रश्न पूछता है (ऐप प्रकार, नाम, रंग, प्लेटफ़ॉर्म) और पूरा प्रोजेक्ट बनाता है।',
    d_t3: '2️⃣ मुक्त निर्माण', d_b3: 'अपनी ऐप का एक वाक्य में वर्णन करें जैसे "5-स्टार रेटिंग वाली रेसिपी साइट"। AI एक मिनट से कम में पूरा कोड बनाता है।',
    d_t4: '3️⃣ AI से चैट', d_b4: 'सरल भाषा में बदलाव माँगें: "डार्क मोड जोड़ें", "बटन हरा करें"। 🎙️ दो माइक्रोफोन उपलब्ध: एक तुरंत वॉइस संदेश भेजता है (लाल बिंदु), दूसरा आपकी आवाज़ को टेक्स्ट फ़ील्ड में लिखता है ताकि भेजने से पहले जांच सकें।',
    d_t5: '4️⃣ तत्काल पूर्वावलोकन', d_b5: 'अपनी ऐप तुरंत चलते देखें, मानो पहले से डिप्लॉय हो चुकी हो। वेब, मोबाइल (PWA) या डेस्कटॉप — आपकी पसंद।',
    d_t6: '5️⃣ ऑफ़लाइन मोड', d_b6: 'इंटरनेट नहीं है? Ollama अपने PC पर लगाकर बिना डेटा भेजे ऐप्स बनाएं। 100% निजी, 100% मुफ़्त।',
    d_t7: 'आज़माने के लिए तैयार?', d_b7: '30 सेकंड में अकाउंट बनाएं — सिर्फ़ ईमेल और पासवर्ड। कोई कार्ड नहीं, कोई विज्ञापन नहीं, कोई कोटा नहीं।',
    mic_voice_send: 'वॉइस संदेश — बोलें और भेजें', mic_voice_text: 'आवाज़ से टेक्स्ट — बोलें और जांचें',
    mic_unsupported: '🎤 इस ब्राउज़र में माइक्रोफ़ोन समर्थित नहीं है।',
    mic_permission: '🎤 कृपया माइक्रोफ़ोन की अनुमति दें।',
    mic_too_short: '🎤 रिकॉर्डिंग बहुत छोटी — पुनः प्रयास करें।',
    mic_no_text: '🎤 आवाज़ नहीं मिली — स्पष्ट बोलें।',
    mic_failed: '🎤 ट्रांसक्रिप्शन विफल। पुनः प्रयास करें।',
    mic_voice_badge: 'वॉइस',
  },

  // ========== বাংলা (Bengali) ==========
  bn: {
    back: 'ফিরে যান', next: 'পরবর্তী', previous: 'পূর্ববর্তী', generate: 'তৈরি করুন',
    loading: 'লোড হচ্ছে…', error: 'ত্রুটি', success: 'সফল', cancel: 'বাতিল',
    save: 'সংরক্ষণ', delete: 'মুছুন', edit: 'সম্পাদনা', close: 'বন্ধ', yes: 'হ্যাঁ', no: 'না',
    loginSignin: 'সাইন ইন', loginSignup: 'সাইন আপ',
    loginConnectToContinue: 'চালিয়ে যেতে সাইন ইন করুন',
    loginCreateAccount: 'আপনার বিনামূল্যে অ্যাকাউন্ট তৈরি করুন',
    loginEmail: 'ইমেইল ঠিকানা (Gmail অনুমোদিত)',
    loginPassword: 'পাসওয়ার্ড', loginName: 'নাম (ঐচ্ছিক)',
    loginSubmitSignin: 'সাইন ইন', loginSubmitSignup: 'অ্যাকাউন্ট তৈরি করুন',
    loginMagicLink: 'ম্যাজিক লিঙ্ক সাইন-ইন (পাসওয়ার্ড ছাড়া)',
    loginForgot: 'পাসওয়ার্ড ভুলে গেছেন?',
    loginSmsDemo: 'SMS সাইন-ইন (ডেমো)',
    loginOrOffline: 'বা অফলাইন মোড',
    loginBackHome: '← হোমে ফিরুন',
    loginHowItWorks: 'এটি কীভাবে কাজ করে', loginLegal: 'শর্তাবলী ও গোপনীয়তা',
    loginWaitingForConfirm: 'নিশ্চিতকরণের অপেক্ষায়…',
    loginEmailMinChars: 'কমপক্ষে ৬ অক্ষর', loginExpiresIn: 'মেয়াদ শেষ হবে',
    loginResendBtn: 'লিঙ্ক পুনরায় পাঠান', loginResendSent: 'পাঠানো হচ্ছে…',
    loginResendCooldown: '১০ মিনিট অপেক্ষা করুন',
    loginIdleNotice: '১ ঘণ্টা বা তার বেশি নিষ্ক্রিয়তার পর আপনি লগ আউট হয়েছেন। এই বার্তা বন্ধ করে আবার সাইন ইন করুন।',
    dashProjects: 'প্রকল্প', dashNewProject: 'নতুন প্রকল্প', dashSwitchAccount: 'অ্যাকাউন্ট বদলান', dashLogout: 'লগ আউট',
    dashOnline: 'অনলাইন', dashOffline: 'অফলাইন', dashAiAvailable: 'AI উপলব্ধ',
    dashTitle: 'CodeForge AI', dashSubtitle: 'সীমাহীন তৈরি',
    dashWhatToDo: 'আপনি কী করতে চান?', dashChooseMode: 'আপনার কাজের মোড বেছে নিন',
    dashEmptyHint: '✨ এখনও কোনো প্রকল্প নেই — শুরু করতে নিচের একটি মোড বেছে নিন (বিনামূল্যে ও সীমাহীন)।',
    dashWizard: 'গাইডেড উইজার্ড', dashWizardDesc: 'সহজ প্রশ্নের সাথে ধাপে ধাপে আপনার প্রকল্প তৈরি করুন',
    dashChat: 'চ্যাট', dashChatBadgeOn: 'অনলাইন AI', dashChatDescOn: 'শক্তিশালী AI-এর সাথে কথা বলুন',
    dashChatBadgeOff: 'অফলাইন AI', dashChatDescOff: 'ইন্টারনেট ছাড়াই স্থানীয় AI (Ollama)',
    dashCreate: 'তৈরি করুন', dashCreateBadgeOn: 'অনলাইন', dashCreateDescOn: 'মোবাইল, ওয়েব, ডেস্কটপ অ্যাপ তৈরি করুন',
    dashCreateBadgeOff: 'অফলাইন', dashCreateDescOff: 'স্থানীয় AI (Ollama) দিয়ে অ্যাপ তৈরি করুন',
    dashInfoOnline: '💡 অনলাইন মোড: রিমোট Ollama সহ শক্তিশালী AI',
    dashInfoOffline: '🔌 অফলাইন মোড: স্থানীয়ভাবে Ollama ইনস্টল থাকা প্রয়োজন',
    dashCollapseSidebar: 'সাইডবার লুকান', dashExpandSidebar: 'প্রকল্প দেখান', dashTutorial: 'টিউটোরিয়াল',
    l_navDiscover: 'অন্বেষণ', l_h1Line1: 'অ্যাপ্লিকেশন তৈরি করুন', l_h1Highlight: 'অ্যাপ্লিকেশন', l_h1Line2: 'কোড না লিখেই',
    l_subtitle: 'আপনার প্রকল্পের বর্ণনা দিন, আমাদের AI তাৎক্ষণিকভাবে সম্পূর্ণ কোড তৈরি করে। ওয়েব, মোবাইল এবং ডেস্কটপ অ্যাপ। সীমাহীন। 100% বিনামূল্যে।',
    l_signupBtn: 'সাইন আপ', l_loginBtn: 'সাইন ইন',
    l_statUnlimited: 'সীমাহীন তৈরি', l_statAI: 'অত্যাধুনিক AI', l_statFormats: 'ওয়েব, মোবাইল, ডেস্কটপ',
    l_featTitle: 'একটি বিপ্লবী প্ল্যাটফর্ম', l_featTitleHighlight: 'বিপ্লবী',
    l_feat1T: 'স্মার্ট জেনারেশন', l_feat1D: 'AI আপনার বর্ণনা বিশ্লেষণ করে তাৎক্ষণিকভাবে পেশাদার কোড তৈরি করে।',
    l_feat2T: 'মোবাইল অ্যাপ (.apk)', l_feat2D: 'সরাসরি Android-এ এক্সপোর্ট করুন। এক ক্লিকে ফোনে ইনস্টল।',
    l_feat3T: 'ডেস্কটপ সফটওয়্যার (.exe)', l_feat3D: 'বিতরণের জন্য প্রস্তুত পেশাদার Windows অ্যাপ তৈরি করুন।',
    l_feat4T: 'ওয়েবসাইট', l_feat4D: 'সমন্বিত হোস্টিং সহ তাৎক্ষণিকভাবে ওয়েবে স্থাপন করুন।',
    l_feat5T: 'অফলাইন মোড', l_feat5D: 'ইন্টারনেট ছাড়াও তৈরি করতে থাকুন। স্বয়ংক্রিয় স্যুইচ।',
    l_feat6T: 'কোনো বিধিনিষেধ নেই', l_feat6D: 'ব্যবহারের সীমা নেই, ক্রেডিট নেই, সম্পূর্ণ সৃজনশীলতা।',
    l_ctaTitle: 'সীমাহীন তৈরি করতে প্রস্তুত?', l_ctaSub: 'AI-সহায়ক উন্নয়ন বিপ্লবে যোগ দিন।',
    l_ctaBtn: 'এখনই শুরু করুন',
    l_footer: '© 2026 CodeForge AI। Emergent AI দ্বারা চালিত। সীমাহীন, কোনো বিধিনিষেধ নেই।',
    d_exit: 'ভ্রমণ ত্যাগ করুন', d_step: 'ধাপ', d_login: 'সাইন ইন',
    d_prev: 'পূর্ববর্তী', d_next: 'পরবর্তী', d_signup: 'সাইন আপ',
    d_kbTip: 'টিপস: নেভিগেট করতে কীবোর্ডের ← → তীর ব্যবহার করুন।',
    d_locked: '🔒 এই বৈশিষ্ট্য ব্যবহার করতে সাইন ইন করুন।', d_preview: 'পূর্বরূপ',
    d_t1: 'CodeForge AI-তে স্বাগতম',
    d_b1: 'এটি আপনার ভবিষ্যৎ ড্যাশবোর্ড। প্রতিটি স্ক্রিন আবিষ্কার করতে তীর ব্যবহার করুন। সাইন আপ করার পরে সব কিছু ব্যবহার করতে পারবেন।',
    d_t2: '1️⃣ গাইডেড উইজার্ড', d_b2: 'AI 4-5টি সহজ প্রশ্ন করে (অ্যাপের ধরন, নাম, রং, প্ল্যাটফর্ম) এবং সম্পূর্ণ প্রকল্প তৈরি করে।',
    d_t3: '2️⃣ মুক্ত তৈরি', d_b3: 'আপনার অ্যাপের একটি বাক্যে বর্ণনা দিন: "5-স্টার রেটিং সহ রেসিপি সাইট"। AI এক মিনিটের কম সময়ে সম্পূর্ণ কোড তৈরি করে।',
    d_t4: '3️⃣ AI-এর সাথে চ্যাট', d_b4: 'সাধারণ ভাষায় পরিবর্তন চান: "ডার্ক মোড যোগ করুন", "বোতাম সবুজ করুন"। 🎙️ দুটি মাইক্রোফোন আছে: একটি তাৎক্ষণিকভাবে ভয়েস বার্তা পাঠায় (লাল বিন্দু), অন্যটি আপনার ভাষণ টেক্সট ফিল্ডে রূপান্তর করে যাতে পাঠানোর আগে দেখতে পারেন।',
    d_t5: '4️⃣ তাৎক্ষণিক পূর্বরূপ', d_b5: 'অ্যাপটি অবিলম্বে চলতে দেখুন, যেন এটি ইতিমধ্যেই স্থাপন করা হয়েছে। ওয়েব, মোবাইল (PWA) বা ডেস্কটপ — আপনার পছন্দ।',
    d_t6: '5️⃣ অফলাইন মোড', d_b6: 'ইন্টারনেট নেই? আপনার পিসিতে Ollama লাগিয়ে ডেটা না পাঠিয়ে অ্যাপ তৈরি করুন। 100% ব্যক্তিগত, 100% বিনামূল্যে।',
    d_t7: 'চেষ্টা করতে প্রস্তুত?', d_b7: '30 সেকেন্ডে অ্যাকাউন্ট তৈরি করুন — শুধু ইমেইল এবং পাসওয়ার্ড। কার্ড নেই, বিজ্ঞাপন নেই, কোটা নেই।',
    mic_voice_send: 'ভয়েস বার্তা — বলুন এবং পাঠান', mic_voice_text: 'ভয়েস টু টেক্সট — বলুন এবং দেখুন',
    mic_unsupported: '🎤 এই ব্রাউজারে মাইক্রোফোন সমর্থিত নয়।',
    mic_permission: '🎤 অনুগ্রহ করে মাইক্রোফোনের অনুমতি দিন।',
    mic_too_short: '🎤 রেকর্ডিং খুব ছোট — আবার চেষ্টা করুন।',
    mic_no_text: '🎤 কোনো বক্তব্য সনাক্ত হয়নি — স্পষ্ট বলুন।',
    mic_failed: '🎤 ট্রান্সক্রিপশন ব্যর্থ। আবার চেষ্টা করুন।',
    mic_voice_badge: 'ভয়েস',
  },

  // ========== Português ==========
  pt: {
    back: 'Voltar', next: 'Seguinte', previous: 'Anterior', generate: 'Gerar',
    loading: 'A carregar…', error: 'Erro', success: 'Sucesso', cancel: 'Cancelar',
    save: 'Guardar', delete: 'Eliminar', edit: 'Editar', close: 'Fechar', yes: 'Sim', no: 'Não',
    loginSignin: 'Entrar', loginSignup: 'Registar',
    loginConnectToContinue: 'Inicia sessão para continuar',
    loginCreateAccount: 'Cria a tua conta gratuita',
    loginEmail: 'Endereço de e-mail (Gmail recomendado)',
    loginPassword: 'Palavra-passe', loginName: 'Nome (opcional)',
    loginSubmitSignin: 'Entrar', loginSubmitSignup: 'Criar conta',
    loginMagicLink: 'Entrar por link mágico (sem palavra-passe)',
    loginForgot: 'Esqueceste a palavra-passe?',
    loginSmsDemo: 'Entrar por SMS (demonstração)',
    loginOrOffline: 'ou modo offline',
    loginBackHome: '← Voltar ao início',
    loginHowItWorks: 'Como funciona', loginLegal: 'Termos e Privacidade',
    loginWaitingForConfirm: 'A aguardar confirmação…',
    loginEmailMinChars: 'Mínimo de 6 caracteres', loginExpiresIn: 'Expira em',
    loginResendBtn: 'Reenviar link', loginResendSent: 'A enviar…',
    loginResendCooldown: 'Aguarda 10 min',
    loginIdleNotice: 'Foste desconectado após 1h ou mais de inatividade. Fecha esta mensagem e inicia sessão novamente.',
    dashProjects: 'Projetos', dashNewProject: 'Novo projeto', dashSwitchAccount: 'Mudar de conta', dashLogout: 'Terminar sessão',
    dashOnline: 'Online', dashOffline: 'Offline', dashAiAvailable: 'IA disponível',
    dashTitle: 'CodeForge AI', dashSubtitle: 'Criação sem limites',
    dashWhatToDo: 'O que queres fazer?', dashChooseMode: 'Escolhe o teu modo de trabalho',
    dashEmptyHint: '✨ Ainda sem projetos — escolhe um modo abaixo para começar (gratuito e ilimitado).',
    dashWizard: 'Assistente guiado', dashWizardDesc: 'Cria o teu projeto passo a passo com perguntas simples',
    dashChat: 'Conversa', dashChatBadgeOn: 'IA ONLINE', dashChatDescOn: 'Conversa com uma IA poderosa',
    dashChatBadgeOff: 'IA OFFLINE', dashChatDescOff: 'IA local (Ollama) sem internet',
    dashCreate: 'Criar', dashCreateBadgeOn: 'ONLINE', dashCreateDescOn: 'Gera apps móvel, web, desktop',
    dashCreateBadgeOff: 'OFFLINE', dashCreateDescOff: 'Gera apps com IA local (Ollama)',
    dashInfoOnline: '💡 Modo online: IA poderosa com Ollama remoto',
    dashInfoOffline: '🔌 Modo offline: requer Ollama instalado localmente',
    dashCollapseSidebar: 'Recolher barra', dashExpandSidebar: 'Mostrar projetos', dashTutorial: 'Tutorial',
    l_navDiscover: 'Descobrir', l_h1Line1: 'Cria Aplicações', l_h1Highlight: 'Aplicações', l_h1Line2: 'Sem Escrever Código',
    l_subtitle: 'Descreve o teu projeto, a nossa IA gera instantaneamente o código completo. Apps web, mobile e desktop. Sem limites. 100% gratuito.',
    l_signupBtn: 'Registar', l_loginBtn: 'Entrar',
    l_statUnlimited: 'Geração Ilimitada', l_statAI: 'IA de Ponta', l_statFormats: 'Web, Mobile, Desktop',
    l_featTitle: 'Uma Plataforma Revolucionária', l_featTitleHighlight: 'Revolucionária',
    l_feat1T: 'Geração Inteligente', l_feat1D: 'A nossa IA analisa a tua descrição e gera código profissional instantaneamente.',
    l_feat2T: 'Apps Mobile (.apk)', l_feat2D: 'Exporta diretamente para Android. Instalação num clique no telemóvel.',
    l_feat3T: 'Software Desktop (.exe)', l_feat3D: 'Cria aplicações Windows profissionais prontas para distribuir.',
    l_feat4T: 'Sites Web', l_feat4D: 'Implanta instantaneamente na web com hosting integrado.',
    l_feat5T: 'Modo Offline', l_feat5D: 'Continua a criar mesmo sem internet. Comutação automática.',
    l_feat6T: 'Sem Restrições', l_feat6D: 'Sem limites de uso. Sem créditos. Criatividade total.',
    l_ctaTitle: 'Pronto para Criar Sem Limites?', l_ctaSub: 'Junta-te à revolução do desenvolvimento assistido por IA.',
    l_ctaBtn: 'Começar Agora',
    l_footer: '© 2026 CodeForge AI. Suportado por Emergent AI. Sem restrições, sem limites.',
    d_exit: 'Sair da visita', d_step: 'Passo', d_login: 'Entrar',
    d_prev: 'Anterior', d_next: 'Seguinte', d_signup: 'Registar',
    d_kbTip: 'Dica: usa as setas ← → do teclado para navegar.',
    d_locked: '🔒 Inicia sessão para usar esta funcionalidade.', d_preview: 'pré-visualização',
    d_t1: 'Bem-vindo ao CodeForge AI',
    d_b1: 'Este é o teu futuro painel. Avança com as setas para descobrir cada ecrã. Após o registo, podes usar tudo.',
    d_t2: '1️⃣ Assistente Guiado', d_b2: 'A IA faz 4-5 perguntas simples (tipo de app, nome, cores, plataforma) e gera o projeto completo.',
    d_t3: '2️⃣ Criação livre', d_b3: 'Descreve a tua app numa frase: «um site de receitas com classificação 5 estrelas». A IA gera o código completo em menos de um minuto.',
    d_t4: '3️⃣ Conversa com a IA', d_b4: 'Pede alterações em linguagem natural: «adiciona modo escuro», «põe o botão verde». 🎙️ Há dois microfones: um envia uma mensagem de voz instantaneamente (ponto vermelho), o outro transcreve a tua voz no campo de texto para reveres antes de enviar.',
    d_t5: '4️⃣ Pré-visualização instantânea', d_b5: 'Vê a tua app a correr imediatamente, como se já estivesse implantada. Web, mobile (PWA) ou desktop — à escolha.',
    d_t6: '5️⃣ Modo Offline', d_b6: 'Sem internet? Com o Ollama instalado no teu PC, gera apps sem enviar dados. 100% privado, 100% gratuito.',
    d_t7: 'Pronto para experimentar?', d_b7: 'Cria a tua conta em 30 segundos — apenas email e palavra-passe. Sem cartão, sem anúncios, sem quotas.',
    mic_voice_send: 'Mensagem de voz — fala e envia', mic_voice_text: 'Voz para texto — fala e revê',
    mic_unsupported: '🎤 Microfone não suportado neste navegador.',
    mic_permission: '🎤 Permite o acesso ao microfone.',
    mic_too_short: '🎤 Gravação demasiado curta — tenta novamente.',
    mic_no_text: '🎤 Nenhuma fala detectada — fala mais claramente.',
    mic_failed: '🎤 Transcrição falhou. Tenta novamente.',
    mic_voice_badge: 'Voz',
  },

  // ========== اردو (Urdu) — RTL ==========
  ur: {
    back: 'واپس', next: 'اگلا', previous: 'پچھلا', generate: 'بنائیں',
    loading: 'لوڈ ہو رہا ہے…', error: 'خرابی', success: 'کامیابی', cancel: 'منسوخ کریں',
    save: 'محفوظ کریں', delete: 'حذف کریں', edit: 'ترمیم', close: 'بند کریں', yes: 'ہاں', no: 'نہیں',
    loginSignin: 'سائن ان', loginSignup: 'سائن اپ',
    loginConnectToContinue: 'جاری رکھنے کے لیے سائن ان کریں',
    loginCreateAccount: 'اپنا مفت اکاؤنٹ بنائیں',
    loginEmail: 'ای میل پتہ (Gmail ترجیحی)',
    loginPassword: 'پاس ورڈ', loginName: 'نام (اختیاری)',
    loginSubmitSignin: 'سائن ان', loginSubmitSignup: 'اکاؤنٹ بنائیں',
    loginMagicLink: 'میجک لنک سائن ان (بغیر پاس ورڈ)',
    loginForgot: 'پاس ورڈ بھول گئے؟',
    loginSmsDemo: 'SMS سائن ان (ڈیمو)',
    loginOrOffline: 'یا آف لائن موڈ',
    loginBackHome: '← ہوم پر واپس',
    loginHowItWorks: 'یہ کیسے کام کرتا ہے', loginLegal: 'شرائط و رازداری',
    loginWaitingForConfirm: 'تصدیق کا انتظار…',
    loginEmailMinChars: 'کم از کم 6 حروف', loginExpiresIn: 'ختم ہونے میں',
    loginResendBtn: 'لنک دوبارہ بھیجیں', loginResendSent: 'بھیجا جا رہا ہے…',
    loginResendCooldown: '10 منٹ انتظار کریں',
    loginIdleNotice: '1 گھنٹے یا زیادہ غیر فعال رہنے کے بعد آپ کو لاگ آؤٹ کر دیا گیا ہے۔ یہ پیغام بند کریں اور دوبارہ سائن ان کریں۔',
    dashProjects: 'پراجیکٹس', dashNewProject: 'نیا پراجیکٹ', dashSwitchAccount: 'اکاؤنٹ تبدیل کریں', dashLogout: 'لاگ آؤٹ',
    dashOnline: 'آن لائن', dashOffline: 'آف لائن', dashAiAvailable: 'AI دستیاب',
    dashTitle: 'CodeForge AI', dashSubtitle: 'لامحدود تخلیق',
    dashWhatToDo: 'آپ کیا کرنا چاہتے ہیں؟', dashChooseMode: 'اپنا کام کا موڈ منتخب کریں',
    dashEmptyHint: '✨ ابھی کوئی پراجیکٹ نہیں — شروع کرنے کے لیے نیچے ایک موڈ منتخب کریں (مفت اور لامحدود)۔',
    dashWizard: 'گائیڈڈ وزرڈ', dashWizardDesc: 'سادہ سوالات کے ساتھ مرحلہ وار اپنا پروجیکٹ بنائیں',
    dashChat: 'گفتگو', dashChatBadgeOn: 'آن لائن AI', dashChatDescOn: 'طاقتور AI سے بات چیت کریں',
    dashChatBadgeOff: 'آف لائن AI', dashChatDescOff: 'انٹرنیٹ کے بغیر مقامی AI (Ollama)',
    dashCreate: 'بنائیں', dashCreateBadgeOn: 'آن لائن', dashCreateDescOn: 'موبائل، ویب، ڈیسک ٹاپ ایپس بنائیں',
    dashCreateBadgeOff: 'آف لائن', dashCreateDescOff: 'مقامی AI (Ollama) سے ایپس بنائیں',
    dashInfoOnline: '💡 آن لائن موڈ: ریموٹ Ollama کے ساتھ طاقتور AI',
    dashInfoOffline: '🔌 آف لائن موڈ: مقامی طور پر Ollama انسٹال ہونا ضروری',
    dashCollapseSidebar: 'سائڈ بار چھپائیں', dashExpandSidebar: 'پراجیکٹس دکھائیں', dashTutorial: 'سبق',
    l_navDiscover: 'دریافت کریں', l_h1Line1: 'ایپلیکیشنز بنائیں', l_h1Highlight: 'ایپلیکیشنز', l_h1Line2: 'کوڈ لکھے بغیر',
    l_subtitle: 'اپنے پراجیکٹ کی وضاحت کریں، ہمارا AI فوراً مکمل کوڈ بنا دیتا ہے۔ ویب، موبائل اور ڈیسک ٹاپ ایپس۔ بغیر حدود کے۔ 100% مفت۔',
    l_signupBtn: 'سائن اپ', l_loginBtn: 'سائن ان',
    l_statUnlimited: 'لامحدود تخلیق', l_statAI: 'جدید ترین AI', l_statFormats: 'ویب، موبائل، ڈیسک ٹاپ',
    l_featTitle: 'ایک انقلابی پلیٹ فارم', l_featTitleHighlight: 'انقلابی',
    l_feat1T: 'ذہین تخلیق', l_feat1D: 'ہمارا AI آپ کی تفصیل کا تجزیہ کرتا ہے اور فوری طور پر پیشہ ور کوڈ تخلیق کرتا ہے۔',
    l_feat2T: 'موبائل ایپس (.apk)', l_feat2D: 'براہ راست Android میں ایکسپورٹ کریں۔ ایک کلک میں موبائل پر انسٹال۔',
    l_feat3T: 'ڈیسک ٹاپ سافٹ ویئر (.exe)', l_feat3D: 'تقسیم کے لیے تیار پیشہ ور Windows ایپلیکیشنز بنائیں۔',
    l_feat4T: 'ویب سائٹس', l_feat4D: 'مربوط ہوسٹنگ کے ساتھ فوری طور پر ویب پر تعینات کریں۔',
    l_feat5T: 'آف لائن موڈ', l_feat5D: 'انٹرنیٹ کے بغیر بھی تخلیق جاری رکھیں۔ خودکار تبدیلی۔',
    l_feat6T: 'کوئی پابندیاں نہیں', l_feat6D: 'کوئی استعمال کی حد نہیں۔ کوئی کریڈٹ نہیں۔ مکمل تخلیقی صلاحیت۔',
    l_ctaTitle: 'لامحدود تخلیق کے لیے تیار؟', l_ctaSub: 'AI سے چلنے والی ترقی کے انقلاب میں شامل ہوں۔',
    l_ctaBtn: 'ابھی شروع کریں',
    l_footer: '© 2026 CodeForge AI۔ Emergent AI کی پشت پناہی۔ بغیر پابندیوں اور حدود کے۔',
    d_exit: 'دورہ ختم کریں', d_step: 'مرحلہ', d_login: 'سائن ان',
    d_prev: 'پچھلا', d_next: 'اگلا', d_signup: 'سائن اپ',
    d_kbTip: 'تجویز: نیویگیٹ کرنے کے لیے کی بورڈ کے ← → تیر استعمال کریں۔',
    d_locked: '🔒 اس فیچر کو استعمال کرنے کے لیے سائن ان کریں۔', d_preview: 'پیش نظارہ',
    d_t1: 'CodeForge AI میں خوش آمدید',
    d_b1: 'یہ آپ کا مستقبل کا ڈیش بورڈ ہے۔ ہر اسکرین دیکھنے کے لیے تیروں کا استعمال کریں۔ سائن اپ کے بعد سب کچھ دستیاب ہوگا۔',
    d_t2: '1️⃣ گائیڈڈ وزرڈ', d_b2: 'AI 4-5 آسان سوالات پوچھتا ہے (ایپ کی قسم، نام، رنگ، پلیٹ فارم) اور مکمل پراجیکٹ بناتا ہے۔',
    d_t3: '2️⃣ آزاد تخلیق', d_b3: 'اپنی ایپ کو ایک جملے میں بیان کریں: "5-اسٹار ریٹنگ والی ترکیب سائٹ"۔ AI ایک منٹ سے کم میں مکمل کوڈ بناتا ہے۔',
    d_t4: '3️⃣ AI کے ساتھ گفتگو', d_b4: 'فطری زبان میں تبدیلیاں مانگیں: "ڈارک موڈ شامل کریں"، "بٹن سبز کریں"۔ 🎙️ دو مائیکروفون دستیاب: ایک فوراً صوتی پیغام بھیجتا ہے (سرخ نقطہ)، دوسرا آپ کی آواز کو متن میں منتقل کرتا ہے تاکہ بھیجنے سے پہلے دیکھ سکیں۔',
    d_t5: '4️⃣ فوری پیش نظارہ', d_b5: 'اپنی ایپ کو فوراً چلتے ہوئے دیکھیں، گویا یہ پہلے ہی تعینات ہو۔ ویب، موبائل (PWA) یا ڈیسک ٹاپ — آپ کا انتخاب۔',
    d_t6: '5️⃣ آف لائن موڈ', d_b6: 'انٹرنیٹ نہیں؟ اپنے PC پر Ollama انسٹال کر کے ڈیٹا بھیجے بغیر ایپس بنائیں۔ 100% نجی، 100% مفت۔',
    d_t7: 'آزمانے کے لیے تیار؟', d_b7: '30 سیکنڈ میں اکاؤنٹ بنائیں — صرف ای میل اور پاس ورڈ۔ کارڈ نہیں، اشتہار نہیں، کوٹا نہیں۔',
    mic_voice_send: 'صوتی پیغام — بولیں اور بھیجیں', mic_voice_text: 'آواز سے متن — بولیں اور جانچیں',
    mic_unsupported: '🎤 اس براؤزر میں مائیکروفون سپورٹ نہیں ہے۔',
    mic_permission: '🎤 براہ کرم مائیکروفون کی اجازت دیں۔',
    mic_too_short: '🎤 ریکارڈنگ بہت مختصر — دوبارہ کوشش کریں۔',
    mic_no_text: '🎤 کوئی آواز نہیں ملی — واضح بولیں۔',
    mic_failed: '🎤 ٹرانسکرپشن ناکام۔ دوبارہ کوشش کریں۔',
    mic_voice_badge: 'آواز',
  }
};

// Supported languages — used by the dropdown selector.
// `label` = name in its own (native) language. `flag` = emoji flag for visual cue.
export const SUPPORTED_LANGS = [
  { code: 'fr', label: 'Français', native: 'FR', flag: '🇫🇷' },
  { code: 'en', label: 'English', native: 'EN', flag: '🇬🇧' },
  { code: 'es', label: 'Español', native: 'ES', flag: '🇪🇸' },
  { code: 'pt', label: 'Português', native: 'PT', flag: '🇵🇹' },
  { code: 'de', label: 'Deutsch', native: 'DE', flag: '🇩🇪' },
  { code: 'nl', label: 'Nederlands', native: 'NL', flag: '🇳🇱' },
  { code: 'ru', label: 'Русский', native: 'RU', flag: '🇷🇺' },
  { code: 'zh', label: '中文 (简体)', native: '中文', flag: '🇨🇳' },
  { code: 'zh-TW', label: '中文 (繁體)', native: '繁體', flag: '🇹🇼' },
  { code: 'hi', label: 'हिन्दी', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', label: 'বাংলা', native: 'বাংলা', flag: '🇧🇩' },
  { code: 'ur', label: 'اردو', native: 'اردو', flag: '🇵🇰' },
];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('codeforge_language');
    if (saved && translations[saved]) return saved;

    const supported = Object.keys(translations);
    const full = (navigator.language || 'en').toLowerCase();
    // Try full code first (e.g. zh-TW), then primary tag (e.g. zh)
    if (supported.includes(full)) return full;
    const primary = full.split('-')[0];
    const exact = supported.find(c => c.toLowerCase() === primary || c.toLowerCase().startsWith(primary + '-'));
    return exact || 'en';
  });

  useEffect(() => {
    localStorage.setItem('codeforge_language', language);
    // Apply RTL direction for Right-to-Left scripts (Urdu, Arabic, Hebrew…)
    try {
      const RTL_LANGS = ['ur', 'ar', 'he', 'fa'];
      const dir = RTL_LANGS.includes(language) ? 'rtl' : 'ltr';
      document.documentElement.setAttribute('dir', dir);
      document.documentElement.setAttribute('lang', language);
    } catch (_) {}
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  // Kept for backwards compatibility — cycles through supported languages.
  const toggleLanguage = () => {
    setLanguage(prev => {
      const codes = Object.keys(translations);
      const idx = codes.indexOf(prev);
      return codes[(idx + 1) % codes.length];
    });
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
